### ISSUE TITLE
sales( item are less add to cart as more than selected)

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#100]
- [ ]  **if we add item in card its takes less what we add item and gave error pop up not able to add** 
- [ ] **customers( later ones we come again back to sales from item that time you  will see customer is already  added for sales** 
- [ ] **not able to add items.**
- [ ] **we cant make payment also (not able to check out )**
![img-20170115-wa0018](https://cloud.githubusercontent.com/assets/24929510/21958914/99809aa4-dade-11e6-8041-bb0be68db10f.jpg)
![img-20170115-wa0015](https://cloud.githubusercontent.com/assets/24929510/21958921/b0e852ea-dade-11e6-828b-d0773c062e82.jpg)
![img-20170115-wa0017](https://cloud.githubusercontent.com/assets/24929510/21958924/c090a198-dade-11e6-8bb6-5b6b244ee146.jpg)

**Comment by Mseenu** [comment]
close
