### ISSUE TITLE
supplier ( while editing supplier , few suppliers phone  number not displaying  

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#101]
supplier ( while editing supplier , few suppliers phone  number not displaying  .
1)  for few suppliers its working properly , 
![ga](https://cloud.githubusercontent.com/assets/25024115/21960888/3d4ec1ac-db1f-11e6-94e8-fdd638f76674.png)
![ga1](https://cloud.githubusercontent.com/assets/25024115/21960889/47323c80-db1f-11e6-8b9f-6eb95534d855.png)
![ga2](https://cloud.githubusercontent.com/assets/25024115/21960894/533dbd7e-db1f-11e6-9c3f-6ce3cf5f47f4.png)

**Comment by dharwadkarR** [comment]
close
