### ISSUE TITLE
Item ( submit is not working some time ) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#102]
-[ ] Item  submit is not working some time. 
- [ ]when we create the item and click enter submit is not take. 
- [ ]while editing the item is not takes submit button 
![122](https://cloud.githubusercontent.com/assets/24929491/21961052/d1fbace2-db25-11e6-8688-46f3fe178914.png)
[exception_20170203174814.txt](https://github.com/GanuM/profitGuruPOS/files/750539/exception_20170203174814.txt)
[info_20170203174814.txt](https://github.com/GanuM/profitGuruPOS/files/750540/info_20170203174814.txt)

**Comment by amarN** [comment]
closed and verified

**Comment by aafrinS** [comment]
still exist

**Comment by knayeem** [comment]
close.

**Comment by dharwadkarR** [comment]
reopen

**Comment by saichaitanyaeruvaram** [comment]
@vijaychhetry :: Hey I have showed you the discount issue, can you debug what is the variability ?

**Comment by vijaychhetry** [comment]
unable to reproduce issue

**Comment by dharwadkarR** [comment]
verified and closed
