### ISSUE TITLE
takeaway(in payment detail Redeem loyalty is not align properly and if we click on print receipt /creat invoice/check out button it shows the pop-up error message))

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#108]
- [ ] in payment detail Redeem loyalty is not align properly.
 - [ ] and if we click on print receipt /create invoice and check out button it shows the pop-up error message.

![17](https://cloud.githubusercontent.com/assets/24931488/21993122/48743672-dc3f-11e6-88be-f8ae5f8b0aa4.png)

**Comment by dharwadkarR** [comment]
issue close
