### ISSUE TITLE
Place order (while add the item it's order quantity takes automatically )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#109]
- [ ] while add the item it's takes order quantity  automatically
![11111](https://cloud.githubusercontent.com/assets/24929491/21993723/592f936e-dc42-11e6-86b1-de102ca154b0.png)

**Comment by GanuM** [comment]
This is feature ,not an bug

**Comment by GanuM** [comment]
@dharwadkarR  contact me for clarification on this issue and close this issue

**Comment by amarN** [comment]
closed and verified
