### ISSUE TITLE
Sales 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#11]
1.can't able make sales items 
2.not able to add customer to sales

**Comment by amarN** [comment]
still exist...
![screenshot from 2017-01-10 15 28 39](https://cloud.githubusercontent.com/assets/24929510/21801872/82809694-d749-11e6-868e-88e128f471e1.png)

**Comment by gajananalienhu** [comment]
![cuuuuuuu](https://cloud.githubusercontent.com/assets/20481449/21916870/60be08bc-d969-11e6-800f-39af09c9bfd0.png)

**Comment by gajananalienhu** [comment]
if we do sale without adding customer or loyalty ,, its working properly ,, if we add adding customer or loyalty, than this problem arising

**Comment by aafrinS** [comment]
bug still exit not able to add customer

**Comment by aafrinS** [comment]
1_) not able to add item to cart 
2_) not able to add customer to sale 
**3_) this problem is arising many times**

**Comment by Mseenu** [comment]
close
