### ISSUE TITLE
takeaway(when we add item to customer shows the following error message)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#110]
- [ ] when we add item to customer shows the following error message.
![18](https://cloud.githubusercontent.com/assets/24931488/21993537/44dabafc-dc41-11e6-83f7-0962502ae66e.png)

**undefined
salesControllerCommonSvc.js:78 PouchDbItem
salesControllerCommonSvc.js:562 Array[4]
configDataSvc.js:133 Calling RestApi: http://localhost:3001/sales/additemRestApi
http://localhost:3001/sales/additemRestApi Failed to load resource: the server responded with a status of 500 (Internal Server Error)
salesServerApis.js:198 Error:  Object
salesControllerCommonSvc.js:1064 Error Message:Error While calling addItem2CartApi(HTTP status500)**

**server side:-**
**You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
exec: internal error
Error: Not Found
    at /home/bk/aamar/ProfitGuru_DAPP_linux2017-01-16-13-00-06/PGServerJs/app.js:178:19
    at Layer.handle [as handle_request] (/home/bk/aamar/ProfitGuru_DAPP_linux2017-01-16-13-00-06/PGServerJs/node_modules/express/lib/router/layer.js:95:5)**

**Comment by moghribalakrishna** [comment]
fixed other issues, need to disable the loyality feature and test that loyality Apis are not getting called after disabling the feature.

**Comment by amarN** [comment]
issued verified and closed
