### ISSUE TITLE
new supplier is not able to add and submit button was not working

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#112]
![20](https://cloud.githubusercontent.com/assets/24931488/21994813/954c7312-dc47-11e6-8330-52a9641f35ee.png)

Calling RestApi: http://localhost:3001/suppliers/create
http://localhost:3001/suppliers/create Failed to load resource: net::ERR_CONNECTION_REFUSED
suppliersServerApis.js:42 Error:  Object
suppliersCntrlr.js:51 Error Message:Error While calling addSupplierApi(HTTP status0)

**server side:-
Error: ConcurrencyError: Session was updated by someone else!
    at /home/bk/aamar/ProfitGuru_DAPP_linux2017-01-16-13-00-06/PGServerJs/node_modules/sessionstore/lib/databases/couchdb.js:133:25
    at /home/bk/aamar/ProfitGuru_DAPP_linux2017-01-16-13-00-06/PGServerJs/node_modules/cradle/lib/cradle/database/documents.js:73:21
    at Request._onResponse [as _callback] (/home/bk/aamar/ProfitGuru_DAPP_linux2017-01-16-13-00-06/PGServerJs/node_modules/cradle/lib/cradle.js:241:20)**

**Comment by amarN** [comment]
issued verified and closed
