### ISSUE TITLE
Counter Order 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#118]
1.while editing the customer in order counter, successful pup-over not displaying 
![c1234](https://cloud.githubusercontent.com/assets/20481136/22005426/094f757a-dc89-11e6-8d3b-fd1bc7eb0775.png)
2.new customer is not adding to counter order.
3.can't able counter order payment

**Comment by GanuM** [comment]
duplicate of  #113

**Comment by amarN** [comment]
duplicate so closed and open in #113
