### ISSUE TITLE
sales ( not able add the customer and if we add item  we are not able to edit its quantity)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#125]
- [x]  if we try to do edit quantity when item is its add to cart we r not able to add and save.
- [ ] in bill details there is alignment problem in which comment box is in comment text
- [x] we are able to make payment without items 
- [x] in receipt the subtotal is alignment is out of bill

![screenshot_2017-01-17-18-43-54](https://cloud.githubusercontent.com/assets/24929491/22022823/8f1146d8-dce9-11e6-9580-517e05295eaf.png)

![screenshot_2017-01-17-19-15-20](https://cloud.githubusercontent.com/assets/24929491/22022839/9a118282-dce9-11e6-923f-7b625476c4e7.png)

**Comment by Mseenu** [comment]
closed
