### ISSUE TITLE
place order SMS and Email

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#127]
1.not working proper send email and text message in place order 
![placeing](https://cloud.githubusercontent.com/assets/20481136/22023989/8c660054-dcee-11e6-8fa2-9ccf1da9514e.png)

**Comment by Mseenu** [comment]
closed and verified

**Comment by aafrinS** [comment]
still exist.

**Comment by knayeem** [comment]
while doing place order we gate error message pop up.and even while adding customer

**Comment by aafrinS** [comment]
1.some supplier not able to add for place order,showin g pop-up.
2. not able to delete all items at a time from cart.
3.not able to send text and email message ,showing pop-up(**no destination available**) even though these are provided in supplier details.
![place order msg](https://cloud.githubusercontent.com/assets/25024115/22180202/fc59066e-e08f-11e6-8f9e-ac5955cf4568.png)

**Comment by saichaitanyaeruvaram** [comment]
@aafrinS  add proper title with more details

**Comment by aafrinS** [comment]
already we are working on place order screen redesign.
