### ISSUE TITLE
Employee ( improper alignment of employee permission and access )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#130]
1.improper alignment of employee permission and access

![1214](https://cloud.githubusercontent.com/assets/24929491/22053956/8aa6e626-dd79-11e6-845f-40f912fbeb07.png)

**Comment by aafrinS** [comment]
- [ ] while adding new employee the comment tool tip shows top of the comment text box

**Comment by amarN** [comment]
-
![email](https://cloud.githubusercontent.com/assets/24929510/22108301/764f5b54-de78-11e6-9f5a-86a3dc19d7dc.png)
 
![screenshot from 2017-01-19 18 48 27](https://cloud.githubusercontent.com/assets/24929510/22108503/804d7428-de79-11e6-8793-427e0402a160.png)

[ ]  we are able to create new employee if we gave any text in e mail  text box.
- [ ] the tool tip is password 1 it should become confirm password**
- [ ] ones edit employee the we get password is already present and password 1 should be confirm password both in tool tip and textbox .

**Comment by aafrinS** [comment]
verified and closed.
