### ISSUE TITLE
Receiving ( in receiving receipt it taking only (yyyy-mm-dd )this format properly .rest all formats its not taking properly.

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#131]
- [ ] in receiving receipt it taking only (yyyy-mm-dd )this format properly .rest all formats its not taking properly.

**Comment by aafrinS** [comment]
in receiving receipt it taking only (yyyy-mm-dd )this format properly .rest all formats its not taking properly.

**Comment by dharwadkarR** [comment]
close
