### ISSUE TITLE
item(in taxes the "derceement option hide automatically. and when we click on deceement tick option its hide both "increement" as well as"decreement "tick option)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#137]
- [x] in taxes the "decrement option hide automatically. 
- [x]  when we click on decrement tick option its hide both "increment" as well as"decrement "tick option.)
- [x] when we edit item and submit and then when we edit same item before clicking edit item it goes to edit by default same as inventory update.
 - [x] while editing the item submit button was not working.
 - [ ]  inventory checking in that text alignment problem in inventory data tracking.
- [ ] while updating inventory does not working submit button.

**Comment by aafrinS** [comment]
verified and closed.
