### ISSUE TITLE
Customer(view option not show in customer list)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#138]
- [ ] view option not show in customer list

![screenshot_2017-01-18-23-19-32](https://cloud.githubusercontent.com/assets/24929491/22076254/5957c552-ddd5-11e6-8d5f-32ad0edcd030.png)

**Comment by GanuM** [comment]
@dharwadkarR  not an bug, contact for clarification

**Comment by Mseenu** [comment]
issue close
