### ISSUE TITLE
Take away (invoice number is not show in sales receipt)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#139]
- [ ] in bill detail when we click on invoice number its hide automatically (DAPP)
![invice](https://cloud.githubusercontent.com/assets/24931488/22102852/f63ac5d4-de5e-11e6-987e-c0736f8e981e.png)
 
- [ ] invoice number is not show in sales receipt(MAPP)
![invice receipt](https://cloud.githubusercontent.com/assets/24931488/22102779/afa5a562-de5e-11e6-84be-e8916072e648.png)

**Comment by Mseenu** [comment]
still exist
