### ISSUE TITLE
Restaurant(when we split the bill and click on complete split button it do not go to payment,it go's restaurant model)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#140]
- [ ] when we split the bill and click on button it doesn't go to payment,its go's restaurant model.

**Comment by Mseenu** [comment]
still exists

**Comment by GanuM** [comment]
This is the functionality , but split has to be implemented yet

**Comment by gajananalienhu** [comment]
invalid ,,, This is the functionality after splinting the bill from table only we need to make payment
