### ISSUE TITLE
Login Home page ( when we click on login button it shows the following pop-up window ) 

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#148]
-[ ] when we click on login button it shows the following pop-up window 
![login](https://cloud.githubusercontent.com/assets/24931488/22108575/cb17d426-de79-11e6-8b3e-9cfffed2261a.png)

**Comment by saichaitanyaeruvaram** [comment]
what is the probability

**Comment by Mseenu** [comment]
issue is cleared kn m not able to find such error
