### ISSUE TITLE
take away and sales(if we add the item which has serial number we are not able to sale that item and we get pop-up error message)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#149]
- [ ] if we add the item which has serial number we are not  able to sale that item and we get pop-up error message.
![seadd](https://cloud.githubusercontent.com/assets/24931488/22114490/b17f81e2-de8f-11e6-94fc-29d3ada52652.png)

**Comment by GanuM** [comment]
as items with serial numbers will be placed separately on different lines in cart (but the item data will be same for both the lines )  , because of this throwing the error while updating sales document ,

"500"
message
:
"Error: Document update conflict."
name
:
"Http500Error"
status
:
"500"

**Comment by gajananalienhu** [comment]
its working properly

**Comment by Mseenu** [comment]
varified and closed
