### ISSUE TITLE
restaurant ( not able to cancel the order ) 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#153]
restaurant ( not able to cancel the order ) 
![cnd](https://cloud.githubusercontent.com/assets/20481449/22171476/0bc64372-dfb5-11e6-9083-7c6366d444cd.png)

**Comment by Mseenu** [comment]
still exist

**Comment by aafrinS** [comment]
still exists

**Comment by Mseenu** [comment]
closed
