### ISSUE TITLE
restaurant( while editing kot if we click on decrease option adding same item with negative mark)

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#154]
restaurant( while editing kot if we click on decrease option adding same item with negative mark)
![dc](https://cloud.githubusercontent.com/assets/20481449/22171692/7e1ac3ea-dfb9-11e6-8e97-5e0cd87d5d7b.png)

**Comment by Mseenu** [comment]
closed and verified
