### ISSUE TITLE
menu item + take away ( for prepared items do not display stock ) 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#155]
1) menu item + take away ( for prepared items do not display stock qty ) 
2) its decreasing and increasing ( we should not able to update stocks for prepared item ) 
it will impact on reports 
![nn](https://cloud.githubusercontent.com/assets/20481449/22171771/b0ad5154-dfbb-11e6-8e5e-56d481ba2e61.png)

**Comment by Mseenu** [comment]
still it is not completed
