### ISSUE TITLE
receiving module make it purchase 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#156]
- [ ]  detailed reports in purchase module in if when we select receiving type it should be purchase type    

![1212](https://cloud.githubusercontent.com/assets/25196499/22427302/7d9b8292-e6b7-11e6-9e54-0b499c933db3.PNG)

**Comment by aafrinS** [comment]
close

**Comment by dharwadkarR** [comment]
verified and close
