### ISSUE TITLE
CUSTOMER(while creating customer if we clear phone number its showing pop-up message)

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#157]
while creating customer if we clear phone number its showing pop-up message)
![customer1](https://cloud.githubusercontent.com/assets/25024115/22174198/92defacc-dffe-11e6-98ac-203d94687201.png)

**Comment by amarN** [comment]
- [ ]  when we create new supplier we get created successfully/ updated successfully
- [ ] it should be while we create new supplier it must show new supplier created sucessfully 
     and when we edit it should bi updated sucessfully

**Comment by saichaitanyaeruvaram** [comment]
we will take this up in next round of fixes

**Comment by aafrinS** [comment]
windows10.

**Comment by aafrinS** [comment]
verified and colsed.
