### ISSUE TITLE
take away (when item comes reorder level it should not showing pop-up )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#163]
- [ ] when item comes reorder level it should not showing pop-up

**Comment by gajananalienhu** [comment]
1) only fast-food we have to display popup if its touched reorder level 
2) do not display popup for prepared items

**Comment by Mseenu** [comment]
still  exist

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
still exist

**Comment by GanuM** [comment]
@gajananalienhu  did you checked this popup issue with prepared item ? if not check and post screen shots

**Comment by Mseenu** [comment]
its not showing popup for fastfood.

**Comment by gajananalienhu** [comment]
@GanuM for fast food also not showing popup 
for prepared i am just remind you while solving this issue it should not affect thats why

**Comment by saichaitanyaeruvaram** [comment]
@gajananalienhu  @Mseenu  please discuss with me

**Comment by dharwadkarR** [comment]
close
