### ISSUE TITLE
Employees permission and access Not working 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#166]
1.If i give access for one employee its not working proper 
![8907](https://cloud.githubusercontent.com/assets/20481136/22179270/e12e628c-e074-11e6-890c-f0f5e86edefb.png)

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
still exist

**Comment by dharwadkarR** [comment]
closed
