### ISSUE TITLE
item ( in item we are able to create same item in same category with case sensitive) 

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#172]
**- [ ] we are able to create same item in same category .**
**- [ ]  if we create same item in same category it should gave pop up message .**

![erroer item](https://cloud.githubusercontent.com/assets/24929510/22180644/3e79bc3a-e09c-11e6-8a0c-f5e05b4f279c.png)

**Comment by gajananalienhu** [comment]
item name and barcode should be unique

**Comment by amarN** [comment]
- [ ] and it also should gave pop up message if we entry duplicate item with same bar code
