### ISSUE TITLE
windows apps ( list of alignment problem ) 

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#175]
- [x]  item list are not in the perfect list alignment problem.
- [ ] the icon should be dark black in all modules ones it is edit .
- [ ]  the alphabet should be dark and bold as it shows output result such as report .
- [ ] in place order ones item add to cart the item are in bold and size is big 
- [x] in sales the item list are not proper alignment
- [ ] in receipt alphabet must be dark and bold     
![error](https://cloud.githubusercontent.com/assets/24929510/22205131/75c47f68-e19b-11e6-90e0-5fccd0d3c31b.PNG)
![capture](https://cloud.githubusercontent.com/assets/24929510/22205188/a469ba22-e19b-11e6-9612-a1ae595dbb36.PNG)
![99](https://cloud.githubusercontent.com/assets/24929510/22205216/c466773e-e19b-11e6-8bb0-70338162bc50.PNG)
![88](https://cloud.githubusercontent.com/assets/24929510/22205223/c9912b6e-e19b-11e6-9d24-12ef74c424f6.PNG)
![33](https://cloud.githubusercontent.com/assets/24929510/22205273/08ecb918-e19c-11e6-9c58-782a4958c784.PNG)
![22](https://cloud.githubusercontent.com/assets/24929510/22205287/155a2b9a-e19c-11e6-97e1-4520a385ac7b.PNG)
![6](https://cloud.githubusercontent.com/assets/24929510/22205297/219623c8-e19c-11e6-998f-a9259ac2f770.PNG)
![15](https://cloud.githubusercontent.com/assets/24929510/22205309/301529a8-e19c-11e6-8417-480f81ae9c69.PNG)
- [ ] tool tips is not  a dark and highlighted this is for all the model .

**Comment by knayeem** [comment]
- [ ] while creating new menu item there is alignment problem in submit button .


![alignment prblm](https://cloud.githubusercontent.com/assets/25196499/22402613/2b646ca6-e5b2-11e6-831d-0ef720c61a9b.PNG)

**Comment by aafrinS** [comment]
employee ( while creating employee comment tool tip should be in center)
![Uploading employee.png…]()

**Comment by aafrinS** [comment]
![alignment item](https://cloud.githubusercontent.com/assets/25024115/22452820/f46aaaf2-e72e-11e6-8558-21e644752183.png)

**Comment by Mseenu** [comment]
closed
