### ISSUE TITLE
Take away(alignment problem)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#177]
- [ ] alignment problem in unsuspended 
- [x] in fast food item we are not able to see price .
- [ ] add to cart is not shown in add item text box while adding to cart
![unsuspended](https://cloud.githubusercontent.com/assets/25196499/22214598/32ccb9f0-e1be-11e6-96c7-4a3bbaad2ffa.png)

![order](https://cloud.githubusercontent.com/assets/25196499/22215576/e1012dc8-e1c1-11e6-9437-2a9f9fdf75a7.png)

**Comment by dharwadkarR** [comment]
close
