### ISSUE TITLE
take order( alignment problem )

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#178]
- [ ] if we don’t select also we are able to take order
![add to cart](https://cloud.githubusercontent.com/assets/24929510/22216971/36b5774c-e1c7-11e6-8363-e2752a8a6721.png)

**Comment by saichaitanyaeruvaram** [comment]
What is the probability?

**Comment by GanuM** [comment]
alignment is fixed , clearing cart is because of same cart across takeorder and takeaway that is logged in #67
