### ISSUE TITLE
take away(OTG item should not add to cart)

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#182]
take away( OTG item should not add to cart)
without price able to add item in cart.
![otg](https://cloud.githubusercontent.com/assets/25024115/22246421/f56b28b0-e25a-11e6-9142-b4d7750e3a7e.png)

**Comment by GanuM** [comment]
@aafrinS this is not an issue , get clarifed

**Comment by gajananalienhu** [comment]
once we submit than only it should display in cart

**Comment by saichaitanyaeruvaram** [comment]
the current behavior is fine
