### ISSUE TITLE
take order(while we add item to the cart in return its showing loading after sometime its showing error pop-up)

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#183]
take order(while we add item to the cart in return its showing loading after sometime its showing error pop-up)
![sss](https://cloud.githubusercontent.com/assets/25024115/22247554/6c5be400-e260-11e6-9e0a-e7bfed49ce76.png)

**Comment by saichaitanyaeruvaram** [comment]
check what is the issue and then close it.

**Comment by GanuM** [comment]
this problem is get resolved after implementing sale return
