### ISSUE TITLE
Retail ( In sales receipt the horizontal lines are incomplete)

### ISSUE THREAD

**Issue by PatilPraveen** [GanuM/profitGuruPOS#184]
Retail ( In sales receipt the horizontal lines are incomplete)

![patil](https://cloud.githubusercontent.com/assets/25224432/22248444/9ff54dac-e264-11e6-93b9-dba456ab3c25.png)

**Comment by Mseenu** [comment]
still exist

**Comment by aafrinS** [comment]
same problem in windows7.

**Comment by PatilPraveen** [comment]
still exist

**Comment by ParshuM** [comment]
closed
