### ISSUE TITLE
Reports ( select date and range not working,)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#196]
select date and range not working,

**Comment by knayeem** [comment]
while receiving id its not showing employee names in drop down

**Comment by dharwadkarR** [comment]
- [ ] when we select sale type is sale/return, the reports are not show. (same as all report)

**Comment by aafrinS** [comment]
in windows7 not showing sales report showing pop-up.
![sales report](https://cloud.githubusercontent.com/assets/25024115/22404054/55253a40-e5dd-11e6-986c-bd0ce3c7a181.png)

**Comment by knayeem** [comment]
verified and closed

**Comment by aafrinS** [comment]
still exist

**Comment by saichaitanyaeruvaram** [comment]
@aafrinS  List out all the problems here

**Comment by ParshuM** [comment]
closed
