### ISSUE TITLE
Customer: once we create customer  id which has been deleted again same customer id is not able to create its happens in supplier too

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#198]
![screenshot_20170126-142140 1](https://cloud.githubusercontent.com/assets/20481136/22325131/cd03ee60-e3d2-11e6-9b39-4d3910750b39.png)

**Comment by Djprem** [comment]
Customer: once we create customer id, which has been deleted once again if we add same customer id it is not able to create its happens in supplier too

**Comment by saichaitanyaeruvaram** [comment]
@uzmaK  reproduce this bug
