### ISSUE TITLE
Reports's are Not working

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#207]
Graphical Reports,Summary Reports, Detailed Reports And Inventory Reports are not working.... Once i click .it showing Error close pop up 
![screenshot_2017-01-26-16-45-11](https://cloud.githubusercontent.com/assets/20493187/22329517/9a467a46-e3e7-11e6-89bb-41ee9ff96e63.png)

**Comment by saichaitanyaeruvaram** [comment]
@Djprem I have enabled few reports. test and make a list of what all is not working.

**Comment by Mseenu** [comment]
closed

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
closed
