### ISSUE TITLE
item and menu item(in inventory data tracking, time type should be changed )

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#208]
-[ ] in the inventory detail in inventory data tracking, time type should be changed.
![rrrrrr](https://cloud.githubusercontent.com/assets/24931488/22396339/7fff8c72-e57c-11e6-9dd3-fb0b3b126ac3.png)

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
closed

**Comment by saichaitanyaeruvaram** [comment]
@Mseenu :: Collect all bugs related to timeformat here and list them. Retail n Restaurant

Include storeconfig timeformat bugs also here

Close any duplicate issue.

**Comment by Mseenu** [comment]
verified and closd
