### ISSUE TITLE
Rename Receivings to Purchase

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#222]

**Comment by GanuM** [comment]
this is already done , please verify it in latest update

**Comment by ParshuM** [comment]
this not done in mobile application

**Comment by knayeem** [comment]
- [ ] In report when we select the details receiving name still there  

![capture](https://cloud.githubusercontent.com/assets/25196499/22401891/ba25086a-e5b2-11e6-80d5-3eb3e6910aab.PNG)

**Comment by Mseenu** [comment]
closed
