### ISSUE TITLE
The following Shortcut keys are not working 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#226]
- [ ] (Place order and purchase),  Not mention any short cut keys. 
- [ ] View category should not be work **Esc** button, same as sales & purchase screen. 
- [ ] Sale ( when we open the suspended sale not work **Esc** button ).
- [ ] sale (we want add item shortcut key ) 
- [x] Item and customer ( while adding Item and customer**Esc** button not working when we click in box ).
- [ ] in item when we click inventory check Esc button not working  
- [x] Report (need **Esc** button on reports).
- [x] store configuration here not work **Esc** button, and when open one setting and {shift+? } key use, there should not be close this window without use Esc button.
- [ ] want to be shortcut key in searching option box.
- [ ] In restaurant module shortcut are not mention 
- [x] In sales, with shortcut keys if we add customer its working properly but shortcut keys window not close Esc  
 
    
![c](https://cloud.githubusercontent.com/assets/24929491/22394235/78d20068-e4e8-11e6-93c0-d796f7f1f457.PNG)

![select sales type](https://cloud.githubusercontent.com/assets/24929491/22394227/24bff35e-e4e8-11e6-95bb-dc8f7e0898b3.PNG)

    
![c](https://cloud.githubusercontent.com/assets/24929491/22394235/78d20068-e4e8-11e6-93c0-d796f7f1f457.PNG)

![select sales type](https://cloud.githubusercontent.com/assets/24929491/22394227/24bff35e-e4e8-11e6-95bb-dc8f7e0898b3.PNG)

**Comment by dharwadkarR** [comment]
still exists

**Comment by ParshuM** [comment]
closed
