### ISSUE TITLE
purchase( invoice option is not working)    

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#229]
- [ ]  replace receiving name in purchase receipt
- [ ] In purchasing cart we click create invoice that time not show invoice number box after we click  the   comment box than its shows.  
 1.
![receipt](https://cloud.githubusercontent.com/assets/24929491/22402851/2832ddb2-e5d3-11e6-9fcb-4ee162cfb56a.PNG)

2. ![receiving replce purchase](https://cloud.githubusercontent.com/assets/24929491/22394337/02bf05ca-e4ec-11e6-89d6-3332488ef25c.PNG)

**Comment by dharwadkarR** [comment]
still exists

**Comment by knayeem** [comment]
closed
