### ISSUE TITLE
purchase ( when we give amount lass than total bill its take pay&finish process )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#230]
- [ ] when we give amount lass than total bill its take pay&finish process 

![22](https://cloud.githubusercontent.com/assets/24929491/22395386/018bc12e-e50b-11e6-8abb-a4726e3bd23f.PNG)

**Comment by GanuM** [comment]
this is fine as per our feature now

**Comment by sushant97** [comment]
without peyment also taking and finish process in restaurant.

**Comment by sushant97** [comment]
close
