### ISSUE TITLE
purchases(in purchasing receipt,instead of disc we need particulars or item as a subtitle )

### ISSUE THREAD

**Issue by PatilPraveen** [GanuM/profitGuruPOS#234]
![hhhh](https://cloud.githubusercontent.com/assets/25224432/22396204/4048dc30-e579-11e6-915d-45a45f906716.png)

**Comment by saichaitanyaeruvaram** [comment]
@GanuM find out the requirement and update

**Comment by PatilPraveen** [comment]
exist in Mapp (sales and purchase).

**Comment by dharwadkarR** [comment]
closed
