### ISSUE TITLE
customer 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#239]
- [ ] ones we assign phone no to customer to one customer and if we try to assign same phone number to another customer it will show pop up text but if we change single digit it will accept phone no and that previous customer who has same phone will dis appear .  

![01](https://cloud.githubusercontent.com/assets/25196499/22403851/dab1a400-e5d8-11e6-9b66-784dfa6bb1e0.PNG)

**Comment by aafrinS** [comment]
in windows10 and windows7.

**Comment by knayeem** [comment]
still exist in windows.

**Comment by knayeem** [comment]
verified and closed issue
