### ISSUE TITLE
Report (alignment problems )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#240]
windows 7 resulation size (1366*768)
- [ ] detailed purchase report alignment problem
- [ ] low inventory there is alignment problem
![ui](https://cloud.githubusercontent.com/assets/24929491/22492136/338ce4f8-e7f6-11e6-8ed5-beaaa5361e32.PNG)
![ui low](https://cloud.githubusercontent.com/assets/24929491/22492144/44661286-e7f6-11e6-861c-7f782d9b1636.PNG)

**Comment by aafrinS** [comment]
1 alignment problem
![report alignment](https://cloud.githubusercontent.com/assets/25024115/22423033/8b37ff10-e6a4-11e6-9eec-4b125f1ae658.png)
2 in tool tip it should be comment.
![tool tip](https://cloud.githubusercontent.com/assets/25024115/22423069/9ff9cfb4-e6a4-11e6-8cd5-1381b86aedc9.png)

**Comment by ParshuM** [comment]
closed
