### ISSUE TITLE
In take away (while adding item in the cart .than  if we  press Esc button it takes loading) 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#242]
- [ ] while adding item in the cart .than  if we  press Esc button it takes loading.

![lalalal](https://cloud.githubusercontent.com/assets/25196499/22414701/7b85e24a-e676-11e6-8843-47686242f0f1.PNG)

**Comment by saichaitanyaeruvaram** [comment]
@GanuM  findout the issue and update the description

**Comment by knayeem** [comment]
verified and closed
