### ISSUE TITLE
take away( alignment problem)

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#245]
take away( before adding customer its showing alignmment problem with item , once we add customer then its showing correct.

![01](https://cloud.githubusercontent.com/assets/25024115/22416212/ed527554-e681-11e6-88db-8bdf6405e8a3.png)

**Comment by saichaitanyaeruvaram** [comment]
@GanuM  find out what is the problem.

**Comment by knayeem** [comment]
verified and closed
