### ISSUE TITLE
Auto Fill and Suggestions All Screens 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#246]
- [ ] 

![hhhh](https://cloud.githubusercontent.com/assets/25196499/22418621/981651d4-e68e-11e6-8c11-6a218bd025fb.PNG)

**Comment by vijaychhetry** [comment]
fixed plz test.. restore window before testing this..

**Comment by knayeem** [comment]
still exist.

**Comment by ParshuM** [comment]
verify and closed
