### ISSUE TITLE
SUMMARY(There is an alignment problem)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#250]
windows 10
-[ 
![summary](https://cloud.githubusercontent.com/assets/25322610/22422467/80d5e9a6-e712-11e6-86ea-22a98deac9d6.png)
]SUMMARY(There is an alignment problem)

**Comment by GanuM** [comment]
@uzmaK mention the resolution

**Comment by uzmaK** [comment]
verified and closed
