### ISSUE TITLE
SALES cart(sales cart is looking ugly.) 

### ISSUE THREAD

**Issue by PatilPraveen** [GanuM/profitGuruPOS#251]
windows 10
-[ ]In sales cart, instead of total quantity just put quantity, then the character will become in one line and digits will become in one line.... because it is looking ugly
![enhancement](https://cloud.githubusercontent.com/assets/25224432/22423238/ad0cf420-e716-11e6-9d09-160d9a2daa24.PNG)

**Comment by ParshuM** [comment]
closed
