### ISSUE TITLE
item(while editing item the quantity & reorder level showing mendetory)

### ISSUE THREAD

**Issue by PatilPraveen** [GanuM/profitGuruPOS#253]
windows 10 and windows 7
-[ ]item(while editing item the quantity & reorder level showing mendetory)

![k](https://cloud.githubusercontent.com/assets/25224432/22426452/4bc618ac-e6cd-11e6-84c5-e7bd2baa2789.PNG)

**Comment by dharwadkarR** [comment]
still exists

**Comment by GanuM** [comment]
@PatilPraveen and @dharwadkarR  now these fields will be mandatory

**Comment by uzmaK** [comment]
closed
