### ISSUE TITLE
(Date format will not showing proper )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#260]
- [ ] Purchasing receipt
- [ ] Sales receipt 
- [ ] Take away receipt  

![333](https://cloud.githubusercontent.com/assets/25196499/22462691/5c6d25da-e7d4-11e6-8bc1-5e7a42f930f5.PNG)

**Comment by GanuM** [comment]
@saichaitanyaeruvaram : should i take it or you will take this anna?

**Comment by knayeem** [comment]
verified and closed
