### ISSUE TITLE
Report ( if we select shortcut button in  report  Esc button not working  ) 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#262]
- [ ] Esc button not working 
- [ ] if i press Esc button we are not able close report page as written in shortcut button 

![12](https://cloud.githubusercontent.com/assets/25196499/22467053/101d2256-e7e9-11e6-995d-c61f98b8f42c.PNG)

**Comment by GanuM** [comment]
@knayeem discuss with me about this issue

**Comment by knayeem** [comment]
verified and closed
