### ISSUE TITLE
purchases("cancel purchases" tool tip shows cancel receiving)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#263]
- [ ]  "cancel purchases" tool tip shows cancel receiving.
- [ ]  while purchasing item from supplier item quantity are adding behind of first number.
       for example: item stock "10" qty after that i have purchasing qty from supplier like "50" but its takes "1050"

**Comment by saichaitanyaeruvaram** [comment]
@Mseenu  Test both the bugs. You could have written a better title.

**Comment by ParshuM** [comment]
closed
