### ISSUE TITLE
item

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#27]
1. no of items shows less in item category.
![items qq](https://cloud.githubusercontent.com/assets/24929510/21804482/3969cf46-d755-11e6-8cd0-ce6a1b399505.png)

![itema vv](https://cloud.githubusercontent.com/assets/24929510/21804494/46dd824e-d755-11e6-9ac0-6a8b5b630e2c.png)

**Comment by dharwadkarR** [comment]
done
