### ISSUE TITLE
Detailed Reports in that date range some field are not disable  

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#273]
![sales11](https://cloud.githubusercontent.com/assets/20481136/22493532/c1933116-e856-11e6-96eb-b162531ef390.png)

**Comment by amarN** [comment]
- [ ] in ubuntu DAAP we are not able to see today sales in list 

![parsu](https://cloud.githubusercontent.com/assets/24929510/22493617/3bfb63c4-e857-11e6-82f6-7d1c29ab15c0.png)

**Comment by ParshuM** [comment]
closed
