### ISSUE TITLE
windows 10(suspended sales.)

### ISSUE THREAD

**Issue by PatilPraveen** [GanuM/profitGuruPOS#274]
-[ ] In suspended sales, comment section is disable.and instead of only date put date/time as a subtitle.
![suspende](https://cloud.githubusercontent.com/assets/25224432/22493994/85989d22-e7e8-11e6-9d8f-65f4e34142e0.PNG)

**Comment by dharwadkarR** [comment]
still exists but the  date and time subtitle  separately

**Comment by ParshuM** [comment]
closed
