### ISSUE TITLE
Windows Installer Tasks

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [GanuM/profitGuruPOS#278]
1. After installation PGDAPP doesn't show on control Panel. Version no has to be present. 
2. Offline Installer - sqlite3, prereq npm install, npm install pgdapp
3. Launch as a service .. 
8. Prereq npm install fails immediately after installing nodejs.. restart required?
9. Uninstaller PGDAPP
10. Installation takes too much time ~15 min

**Comment by omkarsm** [comment]
1, 3, 4 & 5 from issue list is over, need to test.

**Comment by saichaitanyaeruvaram** [comment]
No action required. Open separate bug if required
