### ISSUE TITLE
Purchase(In peyment cart that" cancel" icon is alignment problem)

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#281]
-[ ] In peyment cart that" cancel" icon is alignment problem (located on top of right corner)
![cancel](https://cloud.githubusercontent.com/assets/25447509/22540492/52e296ec-e8d5-11e6-9e09-59176f45cbfd.PNG)

**Comment by saichaitanyaeruvaram** [comment]
@GanuM  Take a session on resolution bugs from Vijay

**Comment by sushant97** [comment]
verified and closed
