### ISSUE TITLE
Windows Server MAPP not working

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#286]

**Comment by saichaitanyaeruvaram** [comment]
@knayeem Give me an update on this issue. Install today's application on all phones (including marketing team).

**Comment by saichaitanyaeruvaram** [comment]
When connected to windows machine, the application is not working.
Pouchdb replication was failing. Disabled windows firewall. Still there were issues.

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by dharwadkarR** [comment]
closed

**Comment by dharwadkarR** [comment]
closed
