### ISSUE TITLE
sales & Purchase (if cancel sales again open  same cart module (10/6))  

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#287]
- [ ] in sales&purchase, if i add item to cart and make payment and we cancel after again same cart display in screen.

**Comment by saichaitanyaeruvaram** [comment]
@dharwadkarR :: Please ask other testers to reproduce this bug and update labels accordingly

**Comment by dharwadkarR** [comment]
only for retail application 
we can add the cart and make payment after cancel then its reproduce

**Comment by knayeem** [comment]
closed
