### ISSUE TITLE
sales checkout is not working (10/4)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#294]
- [ ] when we checkout the bill its not take shows error
![error](https://cloud.githubusercontent.com/assets/24929491/22590520/93d222ec-ea35-11e6-857b-95721af9f78a.PNG)

**Comment by saichaitanyaeruvaram** [comment]
@dharwadkarR :: Reproduce this bug and write the steps to reproduce. Write the probability also.

**Comment by dharwadkarR** [comment]
when we add the customer and make payment that time error is showing

**Comment by GanuM** [comment]
@saichaitanyaeruvaram  im not able to reproduce this , i tried most of the possible cases 
@dharwadkarR are still able to reproduce this ?

**Comment by dharwadkarR** [comment]
now its shows like this type

![ddd](https://cloud.githubusercontent.com/assets/24929491/22645549/96190ca0-ec8d-11e6-90e9-41d6ad4638ec.PNG)

**Comment by dharwadkarR** [comment]
sorry still exsist

**Comment by dharwadkarR** [comment]
when we add two serial no. item its shows error

[info_20170303104804.txt](https://github.com/GanuM/profitGuruPOS/files/815966/info_20170303104804.txt)
[exception_20170303104804.txt](https://github.com/GanuM/profitGuruPOS/files/815967/exception_20170303104804.txt)

**Comment by ParshuM** [comment]
closed
