### ISSUE TITLE
Customer 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#3]
1) if edit the customer its showing error pup-over 
![customer3](https://cloud.githubusercontent.com/assets/20481136/21678904/05af8c50-d367-11e6-8b87-2c1fa89f871f.png)
2)  text character displaying in account filed and phone no filed   
![text1](https://cloud.githubusercontent.com/assets/20481136/21679089/0f4814a2-d368-11e6-81db-632f199268d7.png)

**Comment by aafrinS** [comment]
1)while editing the customer if we change the name its taking submit but not displaying  the customer first  name 
2) while editing account number if enter text character first time than its showing error popup
3) and if we change the account number , its not changing its showing previous one

**Comment by Mseenu** [comment]
close
