### ISSUE TITLE
customer(There should be a cancel symbol button beside search column)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#301]
-[ ] customer(In customer there should be a cancel symbol button beside search column)

![cancel](https://cloud.githubusercontent.com/assets/25322610/22615619/63802bfa-eabe-11e6-9fa1-85a60e20c758.PNG)

**Comment by uzmaK** [comment]
working please fix the bug

**Comment by aafrinS** [comment]
closed.
