### ISSUE TITLE
Make all Entitlements false by defaults

### ISSUE THREAD

**Issue by GanuM** [GanuM/profitGuruPOS#305]

**Comment by moghribalakrishna** [comment]
Done.
  Test the employee creation and their permissions properly.

**Comment by knayeem** [comment]
employee access   and permissions not working properly its shows error 

![rrr](https://cloud.githubusercontent.com/assets/25196499/23654168/46e0410e-02e4-11e7-8749-599aefd305f0.PNG)

**Comment by GanuM** [comment]
Test this feature properly, Its very critical.

**Comment by dharwadkarR** [comment]
not working it should be shows error

**Comment by knayeem** [comment]
closed
