### ISSUE TITLE
Sales(while making bill if we submit showing some error pop up message).

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#310]
-[ ] Sales(while making bill if we submit showing some error pop up message).

![popup msg in sales](https://cloud.githubusercontent.com/assets/25322610/22634328/aa13791e-ec4e-11e6-8f8b-9e2711195d02.PNG)

**Comment by knayeem** [comment]
same problem in Ubuntu
















  
[exception_20170207110023.txt](https://github.com/GanuM/profitGuruPOS/files/757332/exception_20170207110023.txt)
[info_20170207110023.txt](https://github.com/GanuM/profitGuruPOS/files/757333/info_20170207110023.txt)

**Comment by saichaitanyaeruvaram** [comment]
@knayeem @uzmaK @dharwadkarR 

Reproduce this bug and call me immediately. I have added some logs.

**Comment by knayeem** [comment]
closed
