### ISSUE TITLE
Menu Item (while we creating new item its loading blocker )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#316]
- [ ] while we creating new item its loading blocker 
![lod](https://cloud.githubusercontent.com/assets/24929491/22674555/8fbe9414-ed06-11e6-879f-3d65b724ea76.PNG)

![blocker](https://cloud.githubusercontent.com/assets/24929491/22674562/9c2b74ce-ed06-11e6-90f2-80c44478bf2e.PNG)

[npm-debug.txt](https://github.com/GanuM/profitGuruPOS/files/756814/npm-debug.txt)

**Comment by saichaitanyaeruvaram** [comment]
@dharwadkarR :: See if you can reproduce this bug in retail.

**Comment by dharwadkarR** [comment]
close
