### ISSUE TITLE
Suppliers(Add new suppliers and export suppliers icon in between them some little bit space is required)

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#317]
-[ ]
![space in btwn](https://cloud.githubusercontent.com/assets/25447509/22678352/6c023274-ed1f-11e6-9c3a-2867f6b97691.JPG)
(Add new suppliers and export suppliers icon in between them some little bit space is required)

**Comment by knayeem** [comment]
closed
