### ISSUE TITLE
MAAP(when we connected mobile app to UBUNTU its working..but when we connect the same app to windows its not working 

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#318]
- [ ] when we connected mobile app to UBUNTU its working..but when we connect the same app to windows its not working.

**Comment by vijaychhetry** [comment]
- pouchdb , couchdb sync is not happening because cauchdb is not able to communicate with non host clients i.e, MAPP
Hint : plz change cauchdb int config to listen and sync non host client as done in ubuntu

**Comment by GanuM** [comment]
Looks issue is resolved now.

**Comment by knayeem** [comment]
closed
