### ISSUE TITLE
iteam

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#32]
- [ ] creating item in reorder it takes text and category it takes number
- [ ] white editing all the number box takes text also
- [ ] the same issue have restaurant also. 
![text in items](https://cloud.githubusercontent.com/assets/24929510/21805481/698568b6-d75a-11e6-9275-8ba682b90285.png)

**Comment by gajananalienhu** [comment]
issue still exists

**Comment by dharwadkarR** [comment]
close
