### ISSUE TITLE
login ( disable username and password auto fill )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#330]
![capture](https://cloud.githubusercontent.com/assets/24929491/22720530/64fe9942-edd1-11e6-9804-e6ed55f483c7.PNG)

**Comment by saichaitanyaeruvaram** [comment]
@vijaychhetry Ganesh looked at it. He says no 1 is auto-filling the passwords. Find out how the nw is getting the username and password

**Comment by vijaychhetry** [comment]
unable to reproduce issue..

**Comment by dharwadkarR** [comment]
still exists we can reproduce this

**Comment by vijaychhetry** [comment]
fixed plz test.. restore window before testing this..

**Comment by dharwadkarR** [comment]
logout the application the password box shows blanks.but now its shows password

**Comment by ParshuM** [comment]
closed
