### ISSUE TITLE
items(while editing update inventory if we add or sub quantities its not submitting)..windows10

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#332]
-[ ] items(while editing update inventory if we add or sub quantities its not submitting)..

![quantities -](https://cloud.githubusercontent.com/assets/25322610/22725126/2571d094-edf1-11e6-8ec8-016272508ae7.PNG)

**Comment by saichaitanyaeruvaram** [comment]
This is an invalid bug.
The problem was because couchdb was not reset while installing the application.
