### ISSUE TITLE
purchase(adding items in purchase showing error popup).

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#333]
-[ ] purchase(adding items in purchase showing error popup).

![purchase add](https://cloud.githubusercontent.com/assets/25322610/22725369/09b6404a-edf3-11e6-8beb-c64291e7c4a1.PNG)

**Comment by saichaitanyaeruvaram** [comment]
This is an invalid bug.
The problem was because couchdb was not reset while installing the application.
