### ISSUE TITLE
sales(add shops name in sales receipt).

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#336]
-[ ] sales(add shops name in sales receipt).

![add shops name in receipt](https://cloud.githubusercontent.com/assets/25322610/22736947/e962a412-ee26-11e6-9d34-8592a1c00684.PNG)

**Comment by vijaychhetry** [comment]
fixed plz test..!

**Comment by uzmaK** [comment]
still exist

**Comment by vijaychhetry** [comment]
test in new build

**Comment by knayeem** [comment]
verified and closed

**Comment by uzmaK** [comment]
still exist in MAPP not displaying shop name

**Comment by knayeem** [comment]
closed
