### ISSUE TITLE
Sales(bill not showing after click on check out in show error windows 10 and 7)

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#338]
-[ ] 
![bill sales](https://cloud.githubusercontent.com/assets/25447509/22772801/cba3cf70-eec4-11e6-90b5-c127e5151276.PNG)
[exception_20170209111430.txt](https://github.com/GanuM/profitGuruPOS/files/762890/exception_20170209111430.txt)
[info_20170209111430.txt](https://github.com/GanuM/profitGuruPOS/files/762891/info_20170209111430.txt)

bill not showing after click on check out in windows 10

**Comment by uzmaK** [comment]
the serial no. item add 2  and check out that time shows error

**Comment by vijaychhetry** [comment]
Fixed plz test

**Comment by sushant97** [comment]
verified and closed
