### ISSUE TITLE
Apache CouchDB is stopped showing when we run the application in windows 10

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#339]
Name	PID	Description	Status	Group
Apache CouchDB01d2829c440ce310		Apache CouchDB	Stopped	
![aa](https://cloud.githubusercontent.com/assets/24929491/22773066/227ea90e-eec6-11e6-9917-d47872032f34.PNG)

**Comment by saichaitanyaeruvaram** [comment]
fixed
