### ISSUE TITLE
supplier 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#34]
1. while editing the supplier its takes text in  the phone number
2.and if we don’t add email id correctly still it takes submit button
![supplier](https://cloud.githubusercontent.com/assets/24929491/21806060/71f00b52-d75d-11e6-9621-e2ee4a2a3b30.png)

**Comment by gajananalienhu** [comment]
issue still exists

**Comment by Mseenu** [comment]
close
