### ISSUE TITLE
when we connect the printer to system all previous receipt printing automatically  

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#349]

**Comment by GanuM** [comment]
Before Print check if the printer is connected.
http://docs.nwjs.io/en/latest/References/Window/#winprintoptions
http://docs.nwjs.io/en/latest/References/Window/#wingetprinterscallback

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by dharwadkarR** [comment]
closed and verified
