### ISSUE TITLE
Installer Update

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [GanuM/profitGuruPOS#358]
If DB changes migrate db and install update

**Windows Service**

**Installer**
1. Change the SQLiteDB location
    This path is configurable from PGServerJs/config/config.json (relativeSqlLiteDbPath)
2.  Curently CouchDB is reset while installing
3. Checkbox option to cleanup dbs when installing

**Comment by saichaitanyaeruvaram** [comment]
**Notes from TeamViewer Demo**

1. jenkins - plugin to generate checksum for installer
2. send current version in json?
3. Use case Query: Check for upload, Update available -> Download -> download success, but not yet installed -> next time when check for upload, will it download again or is it already taken care?
4. Download partly .. check for option to resume download
5. Lambda Deployment -> make it automatic
6. Update for linux -- later (low priority)
7. Jenkins upload to S3 Bucket

**Comment by saichaitanyaeruvaram** [comment]
Frontend Work: Consume the apis

**Comment by GanuM** [comment]
Updater additions:
> Make the updater service as part of PGServerJs/terminal Node server.
> Read the current version of the software from angualr service in DAPP and package.json in Server sides.
> Adopting versioning using semver and gulpbump for our applications.

**Comment by saichaitanyaeruvaram** [comment]
No action required
