### ISSUE TITLE
item(Employee name should be displayed in inventory details)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#364]
-[ ] Employee name should be displayed in inventory details.

![img-20170214-wa0002](https://cloud.githubusercontent.com/assets/25322610/22918218/402449cc-f2af-11e6-9fa8-e23ad86f0d11.jpg)

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by uzmaK** [comment]
still exist

**Comment by uzmaK** [comment]
verified and closed
