### ISSUE TITLE
Reports(there is an alignment problem in date, employee, subtotal)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#365]
-[ ] there is an alignment problem in date, employee, subtotal

![img-20170214-wa0005](https://cloud.githubusercontent.com/assets/25322610/22918388/26e34dfe-f2b0-11e6-836a-733a09f1483f.jpg)

**Comment by vijaychhetry** [comment]
@ketan-pro is changing the reports ui (deferred )

**Comment by vijaychhetry** [comment]
@ketan-pro is changing the reports ui ( Onhold )

**Comment by dharwadkarR** [comment]
closed
