### ISSUE TITLE
Customer, Employee, Supplier.(beside search column cancel button is not working)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#366]
-[ ] beside search column cancel button is not working

**Comment by vijaychhetry** [comment]
fixed plz test.

**Comment by uzmaK** [comment]
still exist

**Comment by dharwadkarR** [comment]
only supplier working
customer module not have cancel button
employee module not working

**Comment by uzmaK** [comment]
working in DAPP not in MAPP

**Comment by uzmaK** [comment]
customer and employee working supplier not working

**Comment by vijaychhetry** [comment]
test again..

**Comment by uzmaK** [comment]
verified and closed
