### ISSUE TITLE
SALES(showing error popup customersloyality entitlement error: module is not permitted for you,contact your admin))

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#367]
-[ ] SALES(showing error popup customersloyality entitlement error: module is not permitted for you,contact your admin)

![img-20170214-wa0000](https://cloud.githubusercontent.com/assets/25322610/22918702/97819268-f2b1-11e6-9217-aeac09c27805.jpg)

**Comment by dharwadkarR** [comment]
loyalty is hide why this shows pop up

**Comment by uzmaK** [comment]
verified and closed
