### ISSUE TITLE
sales(items are selling with OTG price and taxe..after that in sales receipt it should be display the TAXE amount in receipt)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#369]
- [ ] items selling with OTG price and taxe..  after making payment in sales receipt it should be display the texe amount.(windows 7 also)
![mmmmmm](https://cloud.githubusercontent.com/assets/24931488/22964402/82e88df2-f37e-11e6-981d-abb9537ce275.png)

**Comment by vijaychhetry** [comment]
fixed plz test

**Comment by knayeem** [comment]
verified and closed
