### ISSUE TITLE
If logout application its displaying error pup-over 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#371]
![logout](https://cloud.githubusercontent.com/assets/20481136/23002775/a148dc72-f412-11e6-99a2-0a128f6bf109.png)

**Comment by vijaychhetry** [comment]
how to reproduce the issue..?

**Comment by gajananalienhu** [comment]
login to app and logout ,

**Comment by dharwadkarR** [comment]
fix my side

**Comment by dharwadkarR** [comment]
closed
