### ISSUE TITLE
in sales without amount tendered if we click on pay its showing error 

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#373]
in sales without amount tendered if we click on pay its showing error after that its showing popup for tendered amount 
![pream](https://cloud.githubusercontent.com/assets/20493187/23005431/6c169b56-f422-11e6-8621-560aae569825.png)

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by dharwadkarR** [comment]
still exists
