### ISSUE TITLE
Item ( while we scan bar-code in mobile its take bar-code but shows error pop-up ) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#375]
- [ ] while we scan bar-code in mobile its take bar-code but shows error pop-up 

![screenshot_2017-02-16-11-10-13](https://cloud.githubusercontent.com/assets/24929491/23014932/00e0eb36-f457-11e6-8526-110a0310e84f.png)

**Comment by vijaychhetry** [comment]
duplicate  issue #376

**Comment by dharwadkarR** [comment]
closed
