### ISSUE TITLE
purchases ( while we scan bar-code its take loading after long time shows error pop up )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#376]
- [ ] while we scan bar-code its take loading after long time shows error pop up 

![screenshot_2017-02-16-11-50-38](https://cloud.githubusercontent.com/assets/24929491/23015439/d34bedcc-f458-11e6-9c25-66fd12a790f8.png)

**Comment by ParshuM** [comment]
Closed
