### ISSUE TITLE
Sales ( when we add OTG item in sales cart and add 2 Quantity the total amount show zero(0))

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#379]
- [ ]  when we add OTG item in sales cart and add 2 Quantity the total amount show zero(0).edit and add quantity its not show wrong.

- [ ] while we add two item and one item delete total amount show wrong in below cart.

![otg](https://cloud.githubusercontent.com/assets/24929491/23052934/4cc8392e-f4fb-11e6-88fb-63c5f2f9e088.PNG)

![nn](https://cloud.githubusercontent.com/assets/24929491/23053362/e396a48c-f4fe-11e6-920d-63bde5e3d1eb.PNG)

**Comment by aafrinS** [comment]
verified and closed.
