### ISSUE TITLE
sales  ( alignment problem )

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#4]
1) display the proper UI
![sales2](https://cloud.githubusercontent.com/assets/20481136/21676832/6c55ae58-d35d-11e6-84ba-0b44952e5ee4.png)

**Comment by dharwadkarR** [comment]
1.alignment and text overlapping when we show item
1.![alignment](https://cloud.githubusercontent.com/assets/24929491/21803600/c93aa9c4-d750-11e6-8a57-d62c07a8f863.png)
2.![over lap](https://cloud.githubusercontent.com/assets/24929491/21803615/d444031a-d750-11e6-877a-73285cba252b.png)

**Comment by aafrinS** [comment]
alignment problem item cart card size is not same 
![aa](https://cloud.githubusercontent.com/assets/25024115/21851245/3641debe-d834-11e6-9200-8d3c4fcd58e9.png)

**Comment by gajananalienhu** [comment]
still exists

**Comment by aafrinS** [comment]
close

**Comment by uzmaK** [comment]
still exists reopen

**Comment by GanuM** [comment]
@ParshuM  verify and close this issue

**Comment by Mseenu** [comment]
verified and closed
