### ISSUE TITLE
make home screen like boxes on screen

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#401]
make home screen like boxes on screen 
![20160807_181429 1](https://cloud.githubusercontent.com/assets/20481136/17462488/382b3286-5ccc-11e6-9f26-fa3ca39e4885.jpg)

**Comment by vijaychhetry** [comment]
- [ ] DAPP retail and restaurant
- [ ] MAPP - retail and restaurant

**Comment by vijaychhetry** [comment]
fixed for DAPP

**Comment by uzmaK** [comment]
still not done

**Comment by ParshuM** [comment]
still exit
