### ISSUE TITLE
receiving(return, not able to add items to cart )

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#41]
while returning items to suppliers , items not adding to the cart

**Comment by gajananalienhu** [comment]
while returning items to suppliers , items not adding to the cart

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
still exist

**Comment by dharwadkarR** [comment]
still exist

**Comment by Mseenu** [comment]
close

**Comment by aafrinS** [comment]
still exist.

**Comment by saichaitanyaeruvaram** [comment]
@Mseenu  this issue is duplicate , check and close one

**Comment by ParshuM** [comment]
closed
