### ISSUE TITLE
report enhancement 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#427]
#1) item category 
  Reports by Items Category
2) suppliers 
    Reports By Supplier and their Items.
4) Discounts.
  a) Discounts by category,item,supplier,monthly etc.
5)customers 
all this we can show properly  if count is less if count is more than 20 we can not display it properly we need to change reports design 
7) for tax we have to make two prop-down , we have to include swatch bharat tax, krishi tax, gst, cst, service , sales,

**Comment by aafrinS** [comment]
refer issue number #681,#831,#668.
