### ISSUE TITLE
purchase(while adding items to cart after adding supplier beside 3 dots not working)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#429]
-[ ] (while adding items to cart after adding supplier beside 3 dots not working.)

![default purchase](https://cloud.githubusercontent.com/assets/25322610/23100575/ac4ec326-f6aa-11e6-9c7b-e83441b7fe1b.PNG)

**Comment by knayeem** [comment]
- [ ] supplier name is showing in a right corner and its not showing 'X' symbol.

 
![Uploading suppp.PNG…]()

**Comment by knayeem** [comment]
closed
