### ISSUE TITLE
MAPP Connection Issues

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [GanuM/profitGuruPOS#430]
1 If server is running retail and restaurant apps, the app lists either retail/restaurant - Done
2 After clicking on retail/restaurant server .. it takes to demo page to choose retail/restaurant again - Done
3 Open APP, select some server from history. If you click sales/purchase or any server related calls, the app stops working. App has to be relaunched. - Done
4 GoLive is not working - Done

**Comment by saichaitanyaeruvaram** [comment]
@moghribalakrishna  assign to testers once mapp builder is ready

**Comment by dharwadkarR** [comment]
close
