### ISSUE TITLE
Sales Receipt ( It is Tax related issue)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#438]
- [ ] we added 3 taxes in the sales receipt .but it is showing only 2 taxes.
but it is calculated all 3 taxes in the receipt.

service tax:10%
sales tax:15%
vat:14% 

but in sales receipt it is not showing vat. it is showing only service tax,sales tax.

![sales reciept](https://cloud.githubusercontent.com/assets/25196499/23198650/ff3696ca-f87d-11e6-9701-4d9d3caf0629.PNG)

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by knayeem** [comment]
verified and closed
