### ISSUE TITLE
item kit( submit button not working in item kits.)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#44]
- [ ] submit button not working in item kits.

**Comment by Mseenu** [comment]
1.In item kit there is alignment problem and when creating a new item kit submit button is not working.

**Comment by dharwadkarR** [comment]
![sssa](https://cloud.githubusercontent.com/assets/24929491/21954977/f939d620-da86-11e6-8363-cddbe16943ab.png)
alignment problem  still exists

**Comment by ParshuM** [comment]
closed
