### ISSUE TITLE
modules are not show data(when we open first time modules showing empty after click add(item,customer) option than show list) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#453]

**Comment by vijaychhetry** [comment]
please check the bug..

**Comment by moghribalakrishna** [comment]
@dharwadkarR  , Make sure the bug descriptions are written properly.

**Comment by dharwadkarR** [comment]
application is close and reopen,The customers data is not showing next we click any button than showing data

**Comment by GanuM** [comment]
@dharwadkarR  put screen shots

**Comment by dharwadkarR** [comment]
![image](https://cloud.githubusercontent.com/assets/24929491/25282939/e4af0e74-2666-11e7-84e4-8cf85fa0d03b.png)
after click add item see the data
![image](https://cloud.githubusercontent.com/assets/24929491/25282968/fb5baaba-2666-11e7-8b2f-38133e7635e2.png)
