### ISSUE TITLE
sales(while unsuspend sales causer hand unable to show)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#455]
(while unsuspend sales causer hand unable to show)

![unsuspend](https://cloud.githubusercontent.com/assets/25322610/23289634/246058c4-fa71-11e6-8630-9634f43b347f.png)

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by uzmaK** [comment]
still exist

**Comment by knayeem** [comment]
verified and closed
