### ISSUE TITLE
purchase(in payment there is distance maintained between comment option and comment column)MAPP

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#458]
-[ ] purchase(in payment there is distance maintained between comment option and comment column)![screenshot_2017-02-23-12-11-26](https://cloud.githubusercontent.com/assets/25322610/23295390/393ffe6c-fa25-11e6-900d-ca5b6e34668d.png)

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by ParshuM** [comment]
need moblie app for test

**Comment by uzmaK** [comment]
still exist

**Comment by vijaychhetry** [comment]
fixed plz test..

**Comment by uzmaK** [comment]
verified and closed
