### ISSUE TITLE
Production Version App, Versioning, Continue Jenkins Builder For MAPP

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [GanuM/profitGuruPOS#460]
Production Version App, Versioning, Continue Jenkins Builder For MAPP

**Comment by GanuM** [comment]
- [ ] Currently, Now we can test the MAPP continuously as part of build, as now Its Hosted App part of PGServerJs.
- [ ] Production, version App,

**Comment by saichaitanyaeruvaram** [comment]
Build APK on Jenkins to complete the task

**Comment by GanuM** [comment]
From now on MAPP is available as part of PGServerJs.
