### ISSUE TITLE
item:update inventory- when we click on update inventory all the fields should have read only property except add quantity to add/sub field should have only edit property

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#466]
-[ ] item:update inventory- when we click on update inventory all the fields should have read only property except **quantity to add/sub** field should have only edit property

here all fields are getting edited but not getting updated in the check inventory but its showing inventory updated blank in the column
**note**: quantity to add/sub is getting updated if u click submit
![iu](https://cloud.githubusercontent.com/assets/25322610/23400169/0d4d695a-fdc9-11e6-8edb-24475443f4c9.PNG)

![inventory update](https://cloud.githubusercontent.com/assets/25322610/23400179/18f4307c-fdc9-11e6-8ed3-ed751abbbe2c.PNG)

![iiud](https://cloud.githubusercontent.com/assets/25322610/23400285/811de792-fdc9-11e6-8bd0-972980633154.PNG)

**Comment by knayeem** [comment]
closed issue
