### ISSUE TITLE
Report(in the graphical report the Customer and discounts month is not showing correctly. for ex: 26/00/2017)

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#469]

**Comment by ajaykumarpatil** [comment]
[ ] : in the graphical report the Customer and discounts month is not showing correctly.
for eg: 26/00/2017 
![discounts](https://cloud.githubusercontent.com/assets/26079981/23458045/3ff78532-fe2f-11e6-82ed-2bd7f0c4751a.PNG)

**Comment by saichaitanyaeruvaram** [comment]
@vijaychhetry See if you can debug, else assign back to me.
