### ISSUE TITLE
MAKE RESERVATION

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#47]
1. in make reservation we are not able add start date and other details
2.not able to search the table 
![screenshot_2017-01-11-22-54-49](https://cloud.githubusercontent.com/assets/24929491/21859493/cc47ec64-d852-11e6-9d1f-90bdac61e6c9.png)

**Comment by GanuM** [comment]
#duplicates #82 #96

**Comment by ParshuM** [comment]
closed
