### ISSUE TITLE
Restaurant ( not able to checkout )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#471]
![rr](https://cloud.githubusercontent.com/assets/20481449/23407485/268289e8-fdea-11e6-8828-28b115319b58.PNG)
Restaurant ( not able to checkout ) 

while making payment , not able to checkout ( if we add customer then its working properly 
counter order not able to send for payment

**Comment by gajananalienhu** [comment]
after checkout on receipt its showing error popup

**Comment by saichaitanyaeruvaram** [comment]
@gajananalienhu 

Attach log files.

**Comment by moghribalakrishna** [comment]
This can be added to Restaurant MileStone.

**Comment by ParshuM** [comment]
closed
