### ISSUE TITLE
item while creating same item name of different category name its not taking submit 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#472]
item while creating same item name of different category name its not taking submit 

example 1) santoor is item its comes under soap category 
               2) santoor   is item its comes under powder category 

here it is not taking same name with different category 
same category same item should not take two time 
but same item with different category it should take

**Comment by GanuM** [comment]
We need to make changes to add multiple categories to an item.

**Comment by aafrinS** [comment]
closed
