### ISSUE TITLE
If i sale its not getting checkout its displaying error pup-over #231 build (10\5)

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#476]
![saba](https://cloud.githubusercontent.com/assets/20481136/23450325/881186e6-fe80-11e6-8566-8bd7fabb2f63.png)
[exception_20170301111710.txt](https://github.com/GanuM/profitGuruPOS/files/810397/exception_20170301111710.txt)
[info_20170301111710.TXT](https://github.com/GanuM/profitGuruPOS/files/810400/info_20170301111710.TXT)

**Comment by knayeem** [comment]
closed issue
