### ISSUE TITLE
New Item

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#48]
1.when creating new item the item code alignment problem.
![screenshot_2017-01-11-23-20-29](https://cloud.githubusercontent.com/assets/24929491/21860296/0be49662-d856-11e6-9e99-e631f4d18619.png)
2.when edit the item the quantity and price cost is take text. 
3.spelling mistake in quantity

**Comment by amarN** [comment]
issue closed and verified
