### ISSUE TITLE
purchase(in purchase receipt shop name showing wrong)

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#481]
-[ ] in purchase receipt shop name showing wrong

![screenshot_2017-03-01-11-05-47](https://cloud.githubusercontent.com/assets/25322610/23454269/cf252f22-fe91-11e6-9702-f451bcdc5244.png)

![purchase recipt](https://cloud.githubusercontent.com/assets/25322610/23454500/7263c1b2-fe92-11e6-9d49-be20b71f5f4a.PNG)

**Comment by knayeem** [comment]
closed issue
