### ISSUE TITLE
Purchases in that if i edit quantity display the proper alignment  and not able to pay and finish 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#482]
![purch1](https://cloud.githubusercontent.com/assets/20481136/23457223/03ec6e36-fe9d-11e6-9a12-76a2749ea80d.png)

**Comment by ParshuM** [comment]
![purchse2](https://cloud.githubusercontent.com/assets/20481136/23457432/ef76e750-fe9d-11e6-81d3-9232bf7b5038.png)

**Comment by GanuM** [comment]
- [ ] Description of the issue is not proper.
- [ ] I don't see this issue, see if you can re-produce this?, if so write down detailed steps to reproduce.

**Comment by knayeem** [comment]
closed issue
