### ISSUE TITLE
MI mobile is not show server on MAPP

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#483]
![whatsapp image 2017-03-01 at 4 18 42 pm 1](https://cloud.githubusercontent.com/assets/24929491/23458771/8b321c00-fea3-11e6-80a6-841627910ac5.jpeg)

**Comment by GanuM** [comment]
Looks like Issues is with the NETGEAR Router, connect to DLINK Router and test it, we will have ENTER IP button on SERVERs screen to move on.

**Comment by dharwadkarR** [comment]
closed
