### ISSUE TITLE
Barcode (when we go to retail and editing barcode that time we cant change other values)

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#488]
-[ ] Barcode (when we go to retail and editing barcode that time we cant change other values)
   when editing item barcode that time automatically its saving item.....

**Comment by GanuM** [comment]
re-test this issue, I am not able to reproduce this.

**Comment by sushant97** [comment]
once again i tested that through using barcode scanner same problem will coming..

**Comment by GanuM** [comment]
@dharwadkarR check this and close if it is not valid

**Comment by knayeem** [comment]
closed
