### ISSUE TITLE
Item(Inventory data tracking in that quantity spelling mistake )

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#491]
-[ ] Item(Inventory data tracking in that quantity spells is mistakes)
       quanatity (quantity) like that
![spell mistakes](https://cloud.githubusercontent.com/assets/25447509/23535893/5905b38c-ffe7-11e6-99b8-49130a6be8bb.PNG)

**Comment by dharwadkarR** [comment]
initial quantity spelling mistake

**Comment by sushant97** [comment]
verified and closed
