### ISSUE TITLE
Purchases in that if i add bar code item in cart its displaying error pup-over and bar code number not clearing 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#498]
![bar code 2](https://cloud.githubusercontent.com/assets/20481136/23576639/fb3af7b8-00d0-11e7-84f9-9913bb97a6e0.png)
![bar code 3](https://cloud.githubusercontent.com/assets/20481136/23576641/0222fec2-00d1-11e7-8e79-70947f3c1ca8.png)
![barcode](https://cloud.githubusercontent.com/assets/20481136/23576642/084e5274-00d1-11e7-864d-4dd42c44e722.png)

**Comment by GanuM** [comment]
Fix is made to pop-up One warning, and made changes to clear the search text field.

**Comment by knayeem** [comment]
closed
