### ISSUE TITLE
items 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#5]
if i view items in that price text missing  
![items33](https://cloud.githubusercontent.com/assets/20481136/21679615/0668552e-d36b-11e6-808d-06dd0c0392bc.png)

**Comment by dharwadkarR** [comment]
overlapping of text and price text missing
![items ali and price](https://cloud.githubusercontent.com/assets/24929491/21803421/03f43450-d750-11e6-8db4-86b0f78baa9f.png)
