### ISSUE TITLE
Menu item:-(alignment problem )

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#50]
- [ ] alignment problem 
![alingment](https://cloud.githubusercontent.com/assets/25196499/22213792/6e71d268-e1bb-11e6-9d4b-20a97216ea31.png)

**Comment by Mseenu** [comment]
still exists  #50

**Comment by amarN** [comment]
issue still exist #50

**Comment by dharwadkarR** [comment]
close

**Comment by Mseenu** [comment]
verified and closed

**Comment by aafrinS** [comment]
alignment problem of submit and inventory symbol, while creating item.


![item alignment](https://cloud.githubusercontent.com/assets/25024115/22417747/9e16022c-e68a-11e6-98f5-d2da1a1f2846.png)
