### ISSUE TITLE
Sales(sales cart in that payment details that time when we decrements all the item through shortcut keys its taking load problem)

### ISSUE THREAD

**Issue by sushant97** [GanuM/profitGuruPOS#505]
-[ ]Sales(sales cart in that payment details that time when we decrements all the item through shortcut keys its taking load problem)

[exception_20170305120336.txt](https://github.com/GanuM/profitGuruPOS/files/819251/exception_20170305120336.txt)
[info_20170305120336.txt](https://github.com/GanuM/profitGuruPOS/files/819252/info_20170305120336.txt)
![bugs](https://cloud.githubusercontent.com/assets/25447509/23586688/0b5ebc8c-014f-11e7-91e3-bf7570a43748.PNG)

**Comment by knayeem** [comment]
closed issue
