### ISSUE TITLE
Customer( create 1 customer  and delete, again create a same customer not able to create  )  

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#513]
- [ ]  create 1 customer and delete, again create a same customer not able to create 
![123](https://cloud.githubusercontent.com/assets/25196499/23649308/e64f3ae0-02d2-11e7-8fa6-7fb0774685c7.PNG)

**Comment by dharwadkarR** [comment]
error log files.
[exception_20170307153356.txt](https://github.com/GanuM/profitGuruPOS/files/824463/exception_20170307153356.txt)
[info_20170307153356.txt](https://github.com/GanuM/profitGuruPOS/files/824470/info_20170307153356.txt)

**Comment by knayeem** [comment]
same problem in supplier

**Comment by moghribalakrishna** [comment]
This issue should, exist across all the elements, i.e. items, suppliers, customers etc, as currently platform does not support this.

**Proposed Changes:** 
1) We should pop up the user saying element is already exists and has been deleted in the past, ask the user to either delete the element completely or edit the same.
2) We should have one more window where we show all the deleted elements with options for used to edit them or to delete them completely.

**Comment by saichaitanyaeruvaram** [comment]
Pending: We should have one more window where we show all the deleted elements with options for used to edit them or to delete them completely.

**Comment by dharwadkarR** [comment]
closed
