### ISSUE TITLE
Frontend Work: Consume the apis from Omkar for Installer Update

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [GanuM/profitGuruPOS#514]

**Comment by GanuM** [comment]
pre-requisite from Updater Service:
- [ ] Get the available next-version from Cloud and store that JSON in local couch db.

DAPP dataService:
- [ ]  Will listen for events of above app, and prompt the user accordingly. send the approval/rejection status to the updater service.

**Comment by moghribalakrishna** [comment]
Done closing this.
