### ISSUE TITLE
new build in that displaying old items and customer

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#515]

**Comment by uzmaK** [comment]
![inbuild customers in new build](https://cloud.githubusercontent.com/assets/25322610/23702655/39ad9efc-0422-11e7-8978-013f8700327b.png)

**Comment by dharwadkarR** [comment]
already shows data in new build installed

**Comment by aafrinS** [comment]
its not a bug .it should show previous data until we reset database.
