### ISSUE TITLE
Reports (  sales are not showing in reports  new build  249 )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#517]
- [ ] sales are not showing in reports  new build  249

![reports 123](https://cloud.githubusercontent.com/assets/25196499/23731268/731c08b4-0421-11e7-89a2-64fd5a0d3545.PNG)

**Comment by ParshuM** [comment]
But its displaying in MAPP

**Comment by knayeem** [comment]
closed
