### ISSUE TITLE
Item updating inventory

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#52]
1.in item updating inventory is not able to add quantity and not submitted.
2.in quantity box is text also takes.
3.in other mobile phone same pages line alignment problem
![screenshot_2017-01-12-00-44-51](https://cloud.githubusercontent.com/assets/24929510/21862890/27a9b48a-d861-11e6-9c89-f06bdf53a4f7.png)

![screenshot_2017-01-12-00-29-26](https://cloud.githubusercontent.com/assets/24929491/21862249/65eca214-d85e-11e6-8fc8-fa7f00b8d797.png)

**Comment by amarN** [comment]
duplicate .so  error assign to #75
