### ISSUE TITLE
Employee ( creating new employee showing error )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#523]
- [ ] Employee ( creating new employee showing error ) below all biluid 
- [ ] website DAPP & MAPP
- [ ] cloudmobileapp
- [ ] localdevbuilds  DAPP & MAPP  
- [ ] local installer  DAPP & MAPP

![eerror](https://cloud.githubusercontent.com/assets/24929491/23794423/0cc6ab8c-05b6-11e7-8ea0-c4b547f0758a.PNG)
![image](https://cloud.githubusercontent.com/assets/24929491/24941469/a7141a1e-1eff-11e7-927c-692cbd40c7b6.png)

**Comment by ParshuM** [comment]
verify and closed
