### ISSUE TITLE
in customer module account number should take max 13 numbers it,s taking more then that.

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#533]
in customer module account number should take max 13 numbers it,s taking more then that.
[1] ![customer](https://cloud.githubusercontent.com/assets/20493187/23982907/a74f572e-0a36-11e7-8122-f51ec4430218.PNG)

**Comment by Mseenu** [comment]
check and close

**Comment by dharwadkarR** [comment]
closed
