### ISSUE TITLE
in sales payment details suppose if we entered cash less than total bill it should show pop-up on screen .

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#536]
in sales payment details suppose if we entered cash less than total bill it should show pop-up on screen .
![aaa](https://cloud.githubusercontent.com/assets/20493187/24032635/01e88cea-0b0f-11e7-8542-565369376e47.PNG)

**Comment by moghribalakrishna** [comment]
Prompt User to enter the Remaining Amount.

**Comment by ParshuM** [comment]
verify and closed
