### ISSUE TITLE
Sales (not able to add customer,,and not able to edit quantity ; sales receipt alignment)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#54]
- [x] when we try to add another customer for sale the previous customer name should be display
- [x] in payment mode the payment total should be takes change due and change due should be takes payment total : naming convention of change due and total payments.
- [x] in sales receipt alignment is not proper sub total shows partially
![screenshot_20170111-224144](https://cloud.githubusercontent.com/assets/24931488/21862984/99c09732-d861-11e6-9e6f-66c399d60d3b.png)

![screenshot_20170111-185737](https://cloud.githubusercontent.com/assets/24931488/21862894/2a4a45b0-d861-11e6-9623-105b197f847f.png)
![screenshot_20170111-223229](https://cloud.githubusercontent.com/assets/24931488/21862850/fe83db44-d860-11e6-9a8d-6c0792627d3d.png)

**Comment by dharwadkarR** [comment]
issue close
