### ISSUE TITLE
customer (while adding customer in mobile app by smiles its taking submit and displaying in desktop also )

### ISSUE THREAD

**Issue by uzmaK** [GanuM/profitGuruPOS#545]
-[ ] customer (while adding customer in mobile app by smiles its taking submit and displaying in desktop also ) bug found by hur-e-saba

![xcc](https://cloud.githubusercontent.com/assets/25322610/24134066/c7d8ed80-0e27-11e7-979d-e8804f6da992.PNG)

**Comment by dharwadkarR** [comment]
CLOSED
