### ISSUE TITLE
new supplier not able....to create

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#56]
-[ ] not able to create the new supplier ,submit button not working

![screenshot_2017-01-12-00-56-11](https://cloud.githubusercontent.com/assets/24929510/21863423/649132e0-d863-11e6-8543-5bfc0d0eb88c.png)
- [ ]  while creating new supplier its not showing gender by default.
- [ ] without phone number its taking submit.

**Comment by amarN** [comment]
still exist..#56

**Comment by Mseenu** [comment]
still exist in retail DAPP

**Comment by amarN** [comment]
issue closed and verified

**Comment by aafrinS** [comment]
still exist #56

**Comment by dharwadkarR** [comment]
issue close
