### ISSUE TITLE
item (when view the item screen MRP amount not showing)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#568]
- [x] when view the item screen MRP amount not showing,
- [ ] when view the item discription box alfabets is showing on the right side.

![mrp](https://cloud.githubusercontent.com/assets/25196499/24796626/90cedcc8-1b42-11e7-9ade-ddd562e27505.PNG)

**Comment by vijaychhetry** [comment]
review the bug..

**Comment by dharwadkarR** [comment]
closed issue
