### ISSUE TITLE
purchases in that display the tooltips

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#569]
![tooltip](https://cloud.githubusercontent.com/assets/20481136/24825965/ee07d50a-1c48-11e7-9cd1-2738f82e6c30.png)

**Comment by vijaychhetry** [comment]
give screenshot of issue..

**Comment by dharwadkarR** [comment]
closed issue

**Comment by dharwadkarR** [comment]
closed issue
