### ISSUE TITLE
employee:-before not able to add employee but if i try after sometime i can add the employee .

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#57]
1.When i try to create the new employee the submit will fail

**Comment by amarN** [comment]
issue still exists #57

**Comment by Mseenu** [comment]
still exist

**Comment by amarN** [comment]
- [ ]  while receiving not able to delete item and save 
- [ ] we are not able to see change due ones the receipt is done 
- [ ] not able to written the item

**Comment by amarN** [comment]
- [ ] not able to create new employee

**Comment by ParshuM** [comment]
colsed
