### ISSUE TITLE
Employee in that display the in items access  below mention 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#570]
1.purchases price 
2.mrp
3.purchases tax
4.sales discount 
5.batch id 
6.sales measurement 
![122](https://cloud.githubusercontent.com/assets/20481136/24826105/0a320770-1c4c-11e7-8f94-c553e6b45289.png)

**Comment by ParshuM** [comment]
still exits

**Comment by ParshuM** [comment]
![still exits](https://cloud.githubusercontent.com/assets/20481136/25133605/c528a388-246a-11e7-8d1e-2e36301e49d2.png)

**Comment by knayeem** [comment]
still exists

**Comment by moghribalakrishna** [comment]
isn't this should bug_fixed label? done should be used for new features only.

**Comment by ParshuM** [comment]
verify and closed
