### ISSUE TITLE
Employee in that displaying Receivings   change the purchases  

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#571]
![receivings](https://cloud.githubusercontent.com/assets/20481136/24826336/57ceb60e-1c51-11e7-8b77-2cee10e61401.png)

**Comment by vijaychhetry** [comment]
need more info..

**Comment by dharwadkarR** [comment]
- [ ] change the name receiving to purchase 
- [ ] same screen in report there should be change receiving to purchase
![rrr](https://cloud.githubusercontent.com/assets/24929491/24958980/16015f40-1f46-11e7-9627-a5afc046e5ea.PNG)

**Comment by ParshuM** [comment]
still its exits

**Comment by ParshuM** [comment]
![receivings em](https://cloud.githubusercontent.com/assets/20481136/25133488/6f6afeb4-246a-11e7-9992-ed305b404c91.png)

**Comment by knayeem** [comment]
verified and closed
