### ISSUE TITLE
Sale(one batch item stock is over they should not take more then stock quantity, they should be take next batch quantity but shows pop-up)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#576]
one batch item stock is over they should not take more then stock quantity,
they should be take next batch quantity but shows pop-up

**Comment by Mseenu** [comment]
@dharwadkarR please write a proper sentence...

**Comment by dharwadkarR** [comment]
one batch item is over than shows pop up and should not add to the cart that item

**Comment by Mseenu** [comment]
i am not able to understand the description...plz fix this issue

**Comment by moghribalakrishna** [comment]
@dharwadkarR  very bad you should be writing the issue description properly !!! make sure it doesn't repeat..
Issue is quite different:
  While in sales we should not be displaying batches with empty stock quantity.
