### ISSUE TITLE
Purchase(display the return button click that options shows pop-up) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#584]
display the return button click that options shows pop-up
![p2](https://cloud.githubusercontent.com/assets/24929491/24828346/6d2627e0-1c78-11e7-92d6-0cf6c6a2cb33.PNG)

**Comment by vijaychhetry** [comment]
remove onclick from return button... make it disable.

**Comment by ParshuM** [comment]
closed
