### ISSUE TITLE
Report(In low inventory and inventory summary report change the name (item number to bar code )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#588]
In low inventory and inventory summary report change the name (item number to bar code )

![r3](https://cloud.githubusercontent.com/assets/24929491/24828422/83f9892e-1c7a-11e7-9a1a-24e5f277f8cb.PNG)
![r4](https://cloud.githubusercontent.com/assets/24929491/24828421/83d8b3b6-1c7a-11e7-8bb8-a36be0f66e32.PNG)

**Comment by vijaychhetry** [comment]
change item number to barcode

**Comment by ParshuM** [comment]
still exist

**Comment by ParshuM** [comment]
![still](https://cloud.githubusercontent.com/assets/20481136/25303149/9353c268-276a-11e7-9720-1f6ee25253a7.png)

**Comment by knayeem** [comment]
verified and closed
