### ISSUE TITLE
Store configuration in that general sittings displaying receivings invoice format make its purchases invoice format  

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#589]
![receiving invoice formet](https://cloud.githubusercontent.com/assets/20481136/24828476/987586f4-1c7b-11e7-9d77-e23aa9079ab3.png)

**Comment by knayeem** [comment]
@amarN  Receiving invoice format is closed ..but ( calc.avg  price (receiving ) showing receiving 

![Uploading 1212.PNG…]()

**Comment by knayeem** [comment]
still exists

**Comment by ParshuM** [comment]
verify and closed
