### ISSUE TITLE
items 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#6]
1.while update-ting  inventory. the submit button not working
![updating121](https://cloud.githubusercontent.com/assets/20481136/21679791/e3f3970a-d36b-11e6-94c9-1ac993f6d1dd.png)
2. If I edit items the submit button not working
3. while creating a item getting more number of Taxes
![ttttt](https://cloud.githubusercontent.com/assets/20481136/21680658/266cde8e-d371-11e6-992d-99654f5c0d6c.png)

**Comment by GanuM** [comment]
multiple taxes are allowed
