### ISSUE TITLE
receiving ,, not able to delete item from cart , not able to decrease the item 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#60]
receiving ,, not able to delete item from cart , not able to decrease the item

**Comment by GanuM** [comment]
this api is yet to be implemented in node

**Comment by amarN** [comment]
- [ ] if we edit item it enables all the item for edit.
- [ ] ones payment done .not able to see change due.

**Comment by knayeem** [comment]
not able to save item once we edit.
