### ISSUE TITLE
Add Barcode reader in MAPP

### ISSUE THREAD

**Issue by moghribalakrishna** [GanuM/profitGuruPOS#604]
- [ ] We should add Barcode reader Button to all the places wherever we're expecting user to Enter Barcode.
Ex: While Item creating we're expecting the user to add the barcode.

**Comment by GanuM** [comment]
Done in ALmost all places , @Mseenu check if somewhere is it missing ..

**Comment by Mseenu** [comment]
Done in ALmost all places , @dharwadkarR  check if somewhere is it missing ..

**Comment by dharwadkarR** [comment]
CLOSED
