### ISSUE TITLE
 purchase: If i add one item to the cart some other item is getting added to the cart

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#608]
Steps to reproduce
1. go  purchase screen
2. tap on show all items
3. touch on one item to add that item to cart , this will add some other item to the cart (probably the item of same category)

**Comment by vijaychhetry** [comment]
check is issue exist, if not mark it as done

**Comment by GanuM** [comment]
cause of this bug is height of the cards

**Comment by ParshuM** [comment]
verify and closed
