### ISSUE TITLE
purchase ( when i purchases the items , receipt is showing blank )  ( online web site application )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#616]
- [ ] when i purchase the items , receipt is showing blank

![web purch blank](https://cloud.githubusercontent.com/assets/25196499/24856064/44397c4e-1d98-11e7-9582-1232cf9c5df1.PNG)

**Comment by knayeem** [comment]
![purchase 10](https://cloud.githubusercontent.com/assets/25196499/24856720/90fc8466-1d9a-11e7-911f-447b5ec52856.PNG)

**Comment by knayeem** [comment]
![website puch](https://cloud.githubusercontent.com/assets/25196499/24856765/b545b1c6-1d9a-11e7-9931-4432d7b3b948.PNG)

**Comment by dharwadkarR** [comment]
closed
