### ISSUE TITLE
item (when editing the item bar code  number is not showing ) , online web site application ,

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#617]
- [ ]  when editing the item bar code  number is not showing , (online web site application )

![barrrr](https://cloud.githubusercontent.com/assets/25196499/24857782/5f1ffb5e-1d9e-11e7-92cf-87e287075d82.PNG)

**Comment by vijaychhetry** [comment]
please check is it working in DAPP

**Comment by dharwadkarR** [comment]
closed
