### ISSUE TITLE
Employee not able to create in web site application and displaying error pupover

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#618]
![unknow error](https://cloud.githubusercontent.com/assets/20481136/24858094/6193d832-1e08-11e7-90bf-e7cc36c71235.png)
![m](https://cloud.githubusercontent.com/assets/24929491/25034231/cfed3362-2099-11e7-8f92-51fd736b43a9.PNG)

**Comment by dharwadkarR** [comment]
still exists

**Comment by dharwadkarR** [comment]
closed
