### ISSUE TITLE
employee permission loyalty spelling wrong 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#62]
employee permission loyalty spelling wrong make it loyalty 
![gajaaa](https://cloud.githubusercontent.com/assets/20481449/21916642/efb543fc-d967-11e6-9c54-3fcb94153c39.png)

**Comment by aafrinS** [comment]
1 - [ ] not able to create new employee.
2 - [ ] not able to delete employee.
3- [ ] its not showing gender by default.

**Comment by dharwadkarR** [comment]
issue close
