### ISSUE TITLE
sales history , not able to view history 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#63]
sales history , not able to view history 
![saaa](https://cloud.githubusercontent.com/assets/20481449/21917247/879fc53a-d96c-11e6-8cb0-6ea65816a1d6.png)

**Comment by amarN** [comment]
issue still exists .

**Comment by aafrinS** [comment]
1.still exists .#63
2.after editing quantity in cart we are not  able to save item.
3.if we edit quantity in cart it automatitcally going to the payment .

**Comment by aafrinS** [comment]
in restaurant also stil exists

**Comment by saichaitanyaeruvaram** [comment]
give reprint option

**Comment by ParshuM** [comment]
closed
