### ISSUE TITLE
in employee module while creating  new employee   password showing 2 times it has to shows Ex. ( user name .password .repeat  password)  

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#633]
in employee module while creating  new employee   password showing 2 times it has to shows for  Ex. ( user name .password 
![aaaa](https://cloud.githubusercontent.com/assets/20493187/24906513/9ffd8c30-1ed5-11e7-8f96-71dc51124231.PNG)
and  .repeat  password)

**Comment by vijaychhetry** [comment]
change second password to Re-type password

**Comment by dharwadkarR** [comment]
in employee module while creating new employee password showing 2 times it has to shows Ex. ( user name .password . conform password)

**Comment by Djprem** [comment]
verified and closed

**Comment by Djprem** [comment]
still MAPP

**Comment by ParshuM** [comment]
verify and closed
