### ISSUE TITLE
Sale ( need there arrow mark to identify next options after total)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#637]
- [ ] need there arrow mark to identify next options after total
![m1](https://cloud.githubusercontent.com/assets/24929491/24911784/01a4c3ea-1e81-11e7-9cbc-30cadf21f093.png)

![whatsapp image 2017-04-11 at 5 59 52 am](https://cloud.githubusercontent.com/assets/24929491/24910343/4991905c-1e7c-11e7-86d7-6c45ef5c6b08.jpeg)

**Comment by Mseenu** [comment]
@dharwadkarR please check this  and comment me whether it is write...

**Comment by dharwadkarR** [comment]
new application still exists

**Comment by Mseenu** [comment]
@dharwadkarR check and close

**Comment by ParshuM** [comment]
verify and closed
