### ISSUE TITLE
Displaying Licence info, on DAPP and MAPP.

### ISSUE THREAD

**Issue by moghribalakrishna** [GanuM/profitGuruPOS#639]
- [x] Show server serial number on DAPP and MAPP.
- [x] Licence Info page.
Show the list of clients Licence'd,Host name, Clients applied for licence, Licence Expiry Date etc.

TODO Later:
 a) Adding Distributor info to server.
  b) Activate licence flow.

**Comment by moghribalakrishna** [comment]
GET http://localhost:3000/licence/getAllClientsList should give you list of licence info's authorised and applied.

**Comment by dharwadkarR** [comment]
on about me page 
add serial no. /server Id and client Id
2. change date format in client list 
        In  about me 
          view client list

**Comment by dharwadkarR** [comment]
closed
