### ISSUE TITLE
Purchase ( comment will be taking automatically privies typed comment ) and should not be shows comment in receipt) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#641]
comment will be taking automatically privies typed comment ) and should not be shows comment in receipt
![comment](https://cloud.githubusercontent.com/assets/24929491/24939468/5d611924-1ef2-11e7-9072-532c0cedefc6.PNG)

**Comment by dharwadkarR** [comment]
still exists

**Comment by knayeem** [comment]
verified and closed
