### ISSUE TITLE
sales (if we add the item which has serial number its not showing in receipt )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#642]
- [ ] if we add the item which has serial number its not showing in receipt
- [ ]  if we add the item in the cart tooltips showing  serial number like that 

![serial no](https://cloud.githubusercontent.com/assets/25196499/24939650/bc15b35c-1ef3-11e7-83ad-bc262c1b56a7.PNG)

![0000000](https://cloud.githubusercontent.com/assets/25196499/24941857/4245c71a-1f02-11e7-81ba-fc25a1ddfb2d.PNG)

**Comment by Mseenu** [comment]
check this issue

**Comment by Mseenu** [comment]
@knayeem check and close the issue...

**Comment by knayeem** [comment]
closed issue
