### ISSUE TITLE
item (when edit the item submit button is showing left side )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#645]
- [ ] when edit the item  submit button showing the left side.

![submit showing left](https://cloud.githubusercontent.com/assets/25196499/24950898/68cd5b80-1f27-11e7-920b-e602dede6140.PNG)

**Comment by Mseenu** [comment]
fix this

**Comment by GanuM** [comment]
UI is not aligned properly ... please fix this

**Comment by Mseenu** [comment]
@knayeem check and close this..

**Comment by Mseenu** [comment]
i have fixed that UI alignment...

**Comment by gajananalienhu** [comment]
not done look at submit button make it proper

**Comment by ParshuM** [comment]
verify and closed
