### ISSUE TITLE
sales ( sales edit defaults not working ) 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#65]
1)sales ( sales edit defaults not working ) 
2) not able to delete sales transaction ( sales detailed report)
3) employee name not displaying in  sales detailed report)
4) In windows while open this its show error
![hhhh](https://cloud.githubusercontent.com/assets/20481449/21917662/7a803012-d96f-11e6-909f-ae647d25908b.png)

**Comment by saichaitanyaeruvaram** [comment]
@gajananalienhu  duplicate issue  , close any one among these

**Comment by gajananalienhu** [comment]
let me check one more time

**Comment by ParshuM** [comment]
closed
