### ISSUE TITLE
Item (expiry date should be take automatically) not showing when view the item )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#650]
- [ ] expiry date should be take automatically but not showing on view the item
- [ ] don't click has expiryDate

**Comment by saichaitanyaeruvaram** [comment]
@GanuM  Find out the requirement. It is not clear from the description.
Discuss with @vijaychhetry

**Comment by dharwadkarR** [comment]
now its k( not click it has expiry the expiry is hided
