### ISSUE TITLE
Modules (Db managers and Teime machine not showing in modules ) website app 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#653]
- [ ] Db managers and Teime machine not showing in modules 

![mm](https://cloud.githubusercontent.com/assets/25196499/24994501/f28cb0ec-1fdf-11e7-9800-33eaecbbaa68.PNG)

**Comment by vijaychhetry** [comment]
its not a bug.. its not required in website, only for demo app..

**Comment by ParshuM** [comment]
closed
