### ISSUE TITLE
sale (in below cart total amount is wrong show after adding two three items )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#654]
sale (in cart total amount is wrong show after adding two three items )
![tt](https://cloud.githubusercontent.com/assets/24929491/24999192/7930dbe4-1ff1-11e7-8245-e9458625c5ec.PNG)

**Comment by GanuM** [comment]
Fixed for normal cases ,
When selling price includes tax , then total cart value gets changed , this needs to be handled

**Comment by dharwadkarR** [comment]
closed
