### ISSUE TITLE
Sale ( included tax and serial no. item add to cart price is changing )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#655]
- [ ] before add serial no. price is 5714 after adding serial no. price is change 6000
1. ![b4](https://cloud.githubusercontent.com/assets/24929491/25002924/cb161ae0-2001-11e7-89aa-c894bdf471c5.PNG)

2. ![aftr](https://cloud.githubusercontent.com/assets/24929491/25002958/e6fca0b2-2001-11e7-8c16-95d039d926fd.PNG)

**Comment by Mseenu** [comment]
fix it

**Comment by dharwadkarR** [comment]
closed
