### ISSUE TITLE
Item ( in item screen item does't have any stock shows but in inventory detail there should be show stock ) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#656]
in item screen item does't have any stock shows but in inventory detail there should be show stock 
![item](https://cloud.githubusercontent.com/assets/24929491/25004936/a14c44fa-200b-11e7-93bf-e0858808fe58.PNG) 
![item2](https://cloud.githubusercontent.com/assets/24929491/25004954/b50452da-200b-11e7-953b-524bc57632be.PNG)

**Comment by vijaychhetry** [comment]
please test if already fixed mark it as fixed

**Comment by dharwadkarR** [comment]
closed
