### ISSUE TITLE
Purchase ( in cart add supplier name it should be taking company name and receipt also company name shows )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#659]
![sup](https://cloud.githubusercontent.com/assets/24929491/25035456/aa822e3a-20a2-11e7-9d23-8fba40a8cfa9.PNG)

**Comment by Mseenu** [comment]
@dharwadkarR this is not a bug please check and close this issue.

**Comment by dharwadkarR** [comment]
closed
