### ISSUE TITLE
Item ( Creating one item in item module should be shows same 6 item same data )

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#661]
![coke](https://cloud.githubusercontent.com/assets/24929491/25044494/ccfb5322-20db-11e7-9cc3-dd77ebaed991.PNG)

**Comment by ParshuM** [comment]
![items display du](https://cloud.githubusercontent.com/assets/20481136/25061550/b9a716fc-21d6-11e7-920f-fa8a3396c003.png)
items in that all items displaying double

**Comment by knayeem** [comment]
duplicate #631
