### ISSUE TITLE
item and sales ( tax process is wrong )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#663]
while creating item if we purchase item with inc tax and if we sell exl tax , that item selling as a inc tax only 
example 
purchase item 100 with inc tax 
sell 120 exl tax with 10% , selling price should be 132 rs 
but now its selling price with tax 120 only its taking

**Comment by saichaitanyaeruvaram** [comment]
please test and update the bug or close it

**Comment by aafrinS** [comment]
now process is correct.
