### ISSUE TITLE
item (when edit the item" item name box"showing up )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#666]
- [ ] when edit the item" item name box"showing up 

![drop box](https://cloud.githubusercontent.com/assets/25196499/25061109/56420388-2163-11e7-9a54-924f68b7b17e.PNG)

**Comment by Mseenu** [comment]
@knayeem i have fixed it please check and close the issue...

**Comment by knayeem** [comment]
closed
