### ISSUE TITLE
purchases in that displaying error pup-over (website)

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#670]
![error -pup over](https://cloud.githubusercontent.com/assets/20481136/25063216/4001ba02-21fc-11e7-8815-029addb4b6ad.png)

**Comment by amarN** [comment]
this issue is in website in local its working fyn..

**Comment by ParshuM** [comment]
this bug not there in local its in website only

**Comment by ParshuM** [comment]
this bug not there in local its in website only

**Comment by ParshuM** [comment]
verify and closed

**Comment by ParshuM** [comment]
verify and closed
