### ISSUE TITLE
Purchase (not able add item through bar-code while purchasing ( for bar-code existing item its showing popup )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#673]
not able add item tthrough barcode while purchasing

**Comment by knayeem** [comment]
verified and closed

**Comment by gajananalienhu** [comment]
@GanuM still exists 
steps to reproduce 
1) create item with bar-code add initial quantity 
2) add that item to cart for purchase through barcode

**Comment by knayeem** [comment]
- [ ] if we  tried first time its  not showing error 
- [ ] if we tried second time after clearing the cart its showing error popup

**Comment by dharwadkarR** [comment]
verified and closed
