### ISSUE TITLE
if stock is zero item should not be added in cart 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#675]
if stock is zero item should not be added in cart 

In the cart, there is 1 field currentstock. display the current stock in the message as well

**Comment by GanuM** [comment]
1. add 2 itemsv(a, b) with 0 stock
2. add item a to cart -> it displays stock less than 0 -> press ok
3. add item b to cart -> it displays stock less than 0 2 times -> expected only 1 time

**Comment by aafrinS** [comment]
verified and closed.
