### ISSUE TITLE
if select barcode items its displaying suspend this seles pop-over

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#676]
![if select barcode items its displaying suspend this seles pup-over](https://cloud.githubusercontent.com/assets/20481136/25083098/b122be8a-2372-11e7-8a28-c7af39169f5f.png)

**Comment by GanuM** [comment]
@ParshuM  write proper description of the issue.

**Comment by gajananalienhu** [comment]
@ add item with bar-code and sell that item with bar-code that time it will display  this popup

**Comment by ParshuM** [comment]
still exists

**Comment by ParshuM** [comment]
verify and closed
