### ISSUE TITLE
stock showing as NaN even after purchasing the item and update inventory in item module

### ISSUE THREAD

**Issue by mafeela** [GanuM/profitGuruPOS#679]
**item module**: pineapple is the item name. Stock showing as Nan
if we submit the item without adding initial quantity it shows stock as zero later when we edit the item and submit it then stock show as NaN. later if we add how much stock also its showing as NaN only
![nan stock](https://cloud.githubusercontent.com/assets/26086810/25087346/dbfac4d6-238b-11e7-852d-1c4763e923c0.PNG)
![inv det](https://cloud.githubusercontent.com/assets/26086810/25087366/0cc85d6c-238c-11e7-9d93-d8e2e62cef03.PNG)
![chk inv](https://cloud.githubusercontent.com/assets/26086810/25087395/3a77aaec-238c-11e7-9207-29335621b69f.PNG)

**Comment by aafrinS** [comment]
verified and closed
