### ISSUE TITLE
in item module in" select category"  we add one more option to create category directly  through item module

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#694]
in item module in" select category"  we add one more option to create category directly  through item module

**Comment by Djprem** [comment]
![11](https://cloud.githubusercontent.com/assets/20493187/25380743/f0d379c2-29ce-11e7-9afb-59edb5ab2ad7.PNG)
![22](https://cloud.githubusercontent.com/assets/20493187/25380753/f99fefd6-29ce-11e7-860e-aba8c7581649.PNG)

**Comment by dharwadkarR** [comment]
Add the features in mapp also

**Comment by ParshuM** [comment]
verify and closed
