### ISSUE TITLE
sales ( item,s is taking  automatically serial number in receipt )

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#695]
- [ ] item,s is taking  automatically serial number  in receipt

![0 0](https://cloud.githubusercontent.com/assets/25196499/25112703/ca92961c-23a7-11e7-8939-c9a09eef5126.PNG)

**Comment by Mseenu** [comment]
@knayeem please check and close this issue.... as well as others issues also..

**Comment by knayeem** [comment]
verified and closed
