### ISSUE TITLE
Report(purchase detailed report after open rcvd# id there is an alignment problem submit button)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#700]
- [ ] purchase detailed report after open rcvd# id there should be alignment problem submit button
![purchase r](https://cloud.githubusercontent.com/assets/24929491/25113578/4aabfc08-23ad-11e7-9d08-16886a9f32ee.PNG)

**Comment by ParshuM** [comment]
![id](https://cloud.githubusercontent.com/assets/20481136/25303175/2f2ca308-276b-11e7-8add-0ccf593c88a3.png)

**Comment by ParshuM** [comment]
still exist

**Comment by ajaykumarpatil** [comment]
issue closed
