### ISSUE TITLE
purchase (when purchase the item,s  payments details cancel option and icons showing middle)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#701]
- [ ] when purchase the item,s  payments details cancel option and icons showing middle
- [ ] customer icons also showing middle 
![mideal](https://cloud.githubusercontent.com/assets/25196499/25115155/1a75fb68-23b9-11e7-84d4-f3522349aafb.PNG)

![icicc](https://cloud.githubusercontent.com/assets/25196499/25123764/692d6b22-23de-11e7-8636-e604b241f382.PNG)

**Comment by GanuM** [comment]
@knayeem  provide screen resolution details

**Comment by knayeem** [comment]
closed
