### ISSUE TITLE
application is showing PGServer reconnecting error

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#707]
windows 10
[exception_20170418163402.txt](https://github.com/GanuM/profitGuruPOS/files/928941/exception_20170418163402.txt)
[exception_20170418163653.txt](https://github.com/GanuM/profitGuruPOS/files/928942/exception_20170418163653.txt)

**Comment by saichaitanyaeruvaram** [comment]
@dharwadkarR  write steps to reproduce

**Comment by dharwadkarR** [comment]
CLOSED
