### ISSUE TITLE
Not able to create new customer (ones submit button click its loading]

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#71]
- [ ] Not able to create new customer (ones submit button click its loading and after that we need to reload the application to use )

![loading](https://cloud.githubusercontent.com/assets/24931488/21930542/8c11d946-d9bc-11e6-9cd2-d933c51e540c.png)

**Comment by moghribalakrishna** [comment]
Should be able to add the customer.

**Comment by Mseenu** [comment]
closed
