### ISSUE TITLE
app error ( aqlite_error: no such table profitguru customers )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#717]
app error ( aqlite_error: no such table profitguru customers ) 
this is the error while Creating  item, customer, suppliers,making  sales & purchase all modules its not proceeding to next  screen

**Comment by Djprem** [comment]
![prem issue](https://cloud.githubusercontent.com/assets/20493187/25137770/5b66589e-2476-11e7-9069-0dc61106a043.PNG)
![prem11 issue](https://cloud.githubusercontent.com/assets/20493187/25137781/625e9012-2476-11e7-8132-ce32966b4156.PNG)
![prem 22 issue](https://cloud.githubusercontent.com/assets/20493187/25137795/695599ba-2476-11e7-8c61-67e30ce19639.PNG)

**Comment by Djprem** [comment]
only employee adding

**Comment by gajananalienhu** [comment]
now its working properly
