### ISSUE TITLE
item ( not able to delete item )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#718]
item ( not able to delete item )
![screenshot_2017-04-18-20-58-42-172_com profitgurupos profitgurupos](https://cloud.githubusercontent.com/assets/24929491/25139106/ee21f50a-2479-11e7-83d8-78046f411928.png)

**Comment by saichaitanyaeruvaram** [comment]
write more details.. everytime/random.. which server
is it working now?

**Comment by ParshuM** [comment]
verify and closed
