### ISSUE TITLE
Not able to connect profitguru server ( terminal licence error)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#719]
![ravi](https://cloud.githubusercontent.com/assets/24929491/25138025/450fbc6a-240e-11e7-8fd7-ae77888d818f.PNG)

**Comment by aafrinS** [comment]
![licence](https://cloud.githubusercontent.com/assets/25024115/25579829/0d90bdda-2e99-11e7-8cd0-80885b737739.PNG)
![image](https://cloud.githubusercontent.com/assets/25024115/25579894/a0138ea8-2e99-11e7-859e-1e1bfaad681e.png)

**Comment by saichaitanyaeruvaram** [comment]
get KT on this feature from dev team

**Comment by dharwadkarR** [comment]
closed
