### ISSUE TITLE
customer(not able to add customer popup error message occurs) 

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#72]
- [ ] customer(not able to add customer popup error message occurs) 
![cccccccccc](https://cloud.githubusercontent.com/assets/24931488/21932973/3ee4bd7a-d9c9-11e6-8494-8f18a84eb3a8.png)

**Comment by moghribalakrishna** [comment]
Issue is fixed, should be able to add the customer.

**Comment by Mseenu** [comment]
closed

**Comment by gajananalienhu** [comment]
![11](https://cloud.githubusercontent.com/assets/20481449/22317153/f6bd97a0-e397-11e6-90fd-267d05192a7e.png)

**Comment by saichaitanyaeruvaram** [comment]
@gajananalienhu  What is the probability?

**Comment by gajananalienhu** [comment]
@saichaitanyaeruvaram  if we create customer 10 times than its happening but its depend , after closing app or clearing db

**Comment by saichaitanyaeruvaram** [comment]
@Mseenu reproduce this bug.

Don't switch between retail n restaurant
Don't reset db.

Reproduce

**Comment by saichaitanyaeruvaram** [comment]
closing this bug. If the bug comes again REPOPEN the issue
