### ISSUE TITLE
MAPP Home Screen ReDesign.

### ISSUE THREAD

**Issue by moghribalakrishna** [GanuM/profitGuruPOS#720]

**Comment by moghribalakrishna** [comment]
![1492528649623-544655802](https://cloud.githubusercontent.com/assets/580406/25138514/56d60250-2478-11e7-93d6-c736b58c7282.jpg)
![1492528718311-102711836](https://cloud.githubusercontent.com/assets/580406/25138559/7039b61a-2478-11e7-9e6d-811a752f2a1a.jpg)

**Comment by ParshuM** [comment]
verify and closed
