### ISSUE TITLE
item ( adding item ,import ,export And inventory icons should not come at middle , alignment problem

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#727]
- [ ]  adding item ,import ,export And inventory icons should not come at middle
, alignment problem

![middle](https://cloud.githubusercontent.com/assets/25196499/25168326/ef69c5a0-2497-11e7-84ec-05f4a882dbfb.PNG)

**Comment by aafrinS** [comment]
verified and closed
