### ISSUE TITLE
item , if we view items from category , item info card appearing behind category card 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#73]
item , if we view items from category , item info card appearing behind category card 
![sgggg 04](https://cloud.githubusercontent.com/assets/20481449/21951845/466e4a32-da34-11e6-86bd-9ff645f2bd4e.png)

**Comment by Mseenu** [comment]
closed

**Comment by gajananalienhu** [comment]
still exists
