### ISSUE TITLE
App setting (units setting  while  creating units  its showing  already exists)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#732]
- [ ] units setting  while  creating units  its showing  already exists)

![alredfy](https://cloud.githubusercontent.com/assets/25196499/25173601/93173d5c-24a9-11e7-8c0f-a363cc9f0c7a.PNG)

**Comment by GanuM** [comment]
@knayeem , check weather the unit you are trying to create is already exists ? cross check

**Comment by knayeem** [comment]
verified and closed
