### ISSUE TITLE
purchases 

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#736]

**Comment by Djprem** [comment]
in mobile aap purchase cart allignment problem
![image](https://cloud.githubusercontent.com/assets/20493187/25176561/1f5034be-251c-11e7-8663-5df56be4663b.png)

**Comment by ParshuM** [comment]
still exists

**Comment by ParshuM** [comment]
![image](https://cloud.githubusercontent.com/assets/20481136/25518627/24557e86-2c12-11e7-9080-5fcbb8b708af.png)

**Comment by dharwadkarR** [comment]
clised
