### ISSUE TITLE
Supplier (creating supplier placeholders should be change like that input labels. better to add both it's good)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#737]
![image](https://cloud.githubusercontent.com/assets/24929491/25176763/344bef2e-24b4-11e7-8100-dd540a50dd71.png)
![image](https://cloud.githubusercontent.com/assets/24929491/25176778/4042660a-24b4-11e7-84cb-7208abac54e1.png)

**Comment by Mseenu** [comment]
@dharwadkarR i have fixed this issue....plz check and close

**Comment by dharwadkarR** [comment]
closed
