### ISSUE TITLE
DM management and timeMachine

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#74]
1.if i reset database combos  not clearing in take-way 
![88887](https://cloud.githubusercontent.com/assets/20481136/22004732/30e2cf4c-dc84-11e6-9330-906bcf55473c.png)

![reset database](https://cloud.githubusercontent.com/assets/20481136/21951879/baf01eee-da34-11e6-9f32-9f58e2593148.png)

**Comment by moghribalakrishna** [comment]
Fixed issue for clearing local pouch db's Data

**Comment by Mseenu** [comment]
close

**Comment by dharwadkarR** [comment]
issue close

**Comment by Mseenu** [comment]
still exist

**Comment by Mseenu** [comment]
verified and closed
