### ISSUE TITLE
if we change current net to different application is not working 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#744]
if we change current net to different , application is not working

**Comment by gajananalienhu** [comment]
![network](https://cloud.githubusercontent.com/assets/20481449/25179205/7f90c8f2-2526-11e7-9204-63424b508e5d.PNG)

**Comment by gajananalienhu** [comment]
![net](https://cloud.githubusercontent.com/assets/20481449/25179266/c1110e2c-2526-11e7-8cd9-a68f89ac3a6a.PNG)

**Comment by ParshuM** [comment]
verify and closed
