### ISSUE TITLE
purchase(in total amount digit are in more number)

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#746]
[] : in the purchase while purchasing the item it is showing 
![purchases digits](https://cloud.githubusercontent.com/assets/26079981/25179737/c55819c4-2528-11e7-8e64-2003c8e84118.PNG)
more number of digits in total amount

**Comment by Djprem** [comment]
purchase (when purchase the item,s payments details cancel option and icons showing middle)
![image](https://cloud.githubusercontent.com/assets/20493187/25324383/274b09da-28e3-11e7-9ae6-bfb2c3c85592.png)
![image](https://cloud.githubusercontent.com/assets/20493187/25324403/3ccd41e2-28e3-11e7-9e79-0acc5105932d.png)

**Comment by Djprem** [comment]
purchase, sales(search items close option should display and work) #539
![image](https://cloud.githubusercontent.com/assets/20493187/25324642/8f24a3bc-28e4-11e7-9b92-9019b6ced9de.png)

**Comment by ParshuM** [comment]
verify and closed
