### ISSUE TITLE
ApplicationConfiguration(after deleting one of the category, we can't readd it again)

### ISSUE THREAD

**Issue by sachinvdrit** [GanuM/profitGuruPOS#748]
- [ ] if we delete one of the category, we cant re add it 
 - [ ] if we delete one of the unit, we cant re add it
 - [ ] if we delete one of the discount, we cant re add it
 - [ ] if we delete one of the tax, we cant re add it

![categorysettings](https://cloud.githubusercontent.com/assets/27555856/25180119/681e25e4-252a-11e7-94db-2124d6f78cde.PNG)

**Comment by aafrinS** [comment]
duplicate issue refer issue number #792
