### ISSUE TITLE
item , while updating inventory , not taking submit 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#75]
item , while updating inventory , not taking submit 
![af](https://cloud.githubusercontent.com/assets/20481449/21951900/f9875848-da34-11e6-9d13-a494ae6d6471.png)

**Comment by GanuM** [comment]
#75 ,#85  and #111 seems to be duplicated , verify and keep and remove duplicates and keep any one among these @gajananalienhu  @dharwadkarR  @Mseenu  @amarN

**Comment by amarN** [comment]
verified and closed

**Comment by aafrinS** [comment]
still exist.

**Comment by knayeem** [comment]
close.
