### ISSUE TITLE
EmployeeReport(the new customer name which was typed while billing in the invoice is not visible in Employee report)

### ISSUE THREAD

**Issue by sachinvdrit** [GanuM/profitGuruPOS#751]
- [ ] the new customer name which was typed while billing in the invoice is not visible in Employee report)

![employereport](https://cloud.githubusercontent.com/assets/27555856/25181738/1bb33b76-2530-11e7-814e-6e55da9c3a10.PNG)

**Comment by knayeem** [comment]
duplicate #572
