### ISSUE TITLE
Report(in employee report it is showing both payment type and payment, instead of only payment type)

### ISSUE THREAD

**Issue by sachinvdrit** [GanuM/profitGuruPOS#752]
- [ ] in employee report it is showing both payment type and payment, instead of only payment type.

![employeereportpaytype](https://cloud.githubusercontent.com/assets/27555856/25182300/cab3d120-2531-11e7-8156-1d92d0ed7550.PNG)

**Comment by GanuM** [comment]
@sachinvdrit  this is not an bug , contact me for further clarification

**Comment by aafrinS** [comment]
verified and closed.
