### ISSUE TITLE
Report ( in detailed Employee report there is alignment problem)  

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#754]
amounts
![image](https://cloud.githubusercontent.com/assets/24929491/25184422/398069e6-24cf-11e7-8a5f-67bc3d807f37.png)

**Comment by ParshuM** [comment]
verify and closed

**Comment by ParshuM** [comment]
still exist

**Comment by ParshuM** [comment]
still exist

**Comment by ParshuM** [comment]
![image](https://cloud.githubusercontent.com/assets/20481136/25526408/05ee1cea-2c31-11e7-9688-b6fe852c9c96.png)
