### ISSUE TITLE
Report (inventory summery report there should be shows next option.If click next option  it's showing blank)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#755]
![image](https://cloud.githubusercontent.com/assets/24929491/25185684/dc140bc4-24d2-11e7-840b-45c9f951371f.png)
![image](https://cloud.githubusercontent.com/assets/24929491/25185694/e1de2b20-24d2-11e7-8399-f1ccae3a269a.png)

**Comment by Mseenu** [comment]
close it and there is no option for next.....

**Comment by dharwadkarR** [comment]
closed
