### ISSUE TITLE
Reports(in graphical reports showing more digits)

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#758]
[] : In Graphical reports all modules values are showing more number of digits.
![longscreenshot_2017-04-19-12-58-09](https://cloud.githubusercontent.com/assets/26079981/25218248/d798c210-25c7-11e7-8df3-89ee474c00cd.png)
![longscreenshot_2017-04-19-13-02-26](https://cloud.githubusercontent.com/assets/26079981/25218249/d79e78b8-25c7-11e7-940f-623262ae65f9.png)
![longscreenshot_2017-04-19-13-03-53](https://cloud.githubusercontent.com/assets/26079981/25218250/d7a9f4ae-25c7-11e7-986d-839d2f665f56.png)
![longscreenshot_2017-04-19-13-04-11](https://cloud.githubusercontent.com/assets/26079981/25218251/d7b0c3e2-25c7-11e7-955e-c05317ff8d93.png)
![longscreenshot_2017-04-19-13-08-42](https://cloud.githubusercontent.com/assets/26079981/25218252/d7f5c03c-25c7-11e7-929f-1eae3aae4629.png)
![Uploading LongScreenshot_2017-04-19-13-09-18.png…]()

**Comment by Mseenu** [comment]
fixed....

**Comment by ajaykumarpatil** [comment]
closed
