### ISSUE TITLE
Report(in the graphical report the Customer and discounts month is not showing )

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#759]
[] : In the  graphical report the Customer and discounts month is not showing properly 
eg: it is showing 19/00/2017
![longscreenshot_2017-04-19-13-02-00](https://cloud.githubusercontent.com/assets/26079981/25218584/f2d58f44-25c8-11e7-9eac-62ce90971df4.png)

**Comment by knayeem** [comment]
duplicate #469
