### ISSUE TITLE
Menu item while creating new item, not taking submit

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#76]
- [ ] Menu item while creating new item, not taking submit
![iiii](https://cloud.githubusercontent.com/assets/20481136/21951964/07623e28-da36-11e6-8755-4b1c76b70022.png)

**Comment by amarN** [comment]
still exist #76 
- [ **] not able to add item and inventory update in which we are not able to click submit button**

**Comment by Mseenu** [comment]
closed
