### ISSUE TITLE
customer ( while editing customer two popup messages showing )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#78]
customer ( while editing customer two popup messages showing )
,, 1) while editing popup should not be appear
![gaja3](https://cloud.githubusercontent.com/assets/20481449/21951978/7db74636-da36-11e6-8e42-10cfb676c62c.png)
![gaja4](https://cloud.githubusercontent.com/assets/20481449/21951980/855803f8-da36-11e6-93d1-32ca9038cd5f.png)

 on screen before submit ,

**Comment by amarN** [comment]
closed
