### ISSUE TITLE
in sales 1)  i add otg item to cart and suspend it 2) then i went  to suspeded sales  and try to un - suspend it  it,s show,s this error

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#786]
in sales 1)  i add otg item to cart and suspend it 2) then i went  to suspeded sales  and try to un - suspend it  it,s show,s this error
![suspeded2](https://cloud.githubusercontent.com/assets/20493187/25273050/c60e76ee-26a7-11e7-9cbe-8253a6d0c472.PNG)
![suspended sale](https://cloud.githubusercontent.com/assets/20493187/25273052/c649baba-26a7-11e7-8bbd-3f9865918433.PNG)

**Comment by aafrinS** [comment]
verified and closed
