### ISSUE TITLE
Application setting (when i edit the discount expiry date  showing wrong)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#791]
- [ ]  (when i edit the discount expiry date  showing wrong)

![expiry](https://cloud.githubusercontent.com/assets/25196499/25277501/8eca1192-26bc-11e7-9a90-82b4ab5aa653.PNG)

**Comment by GanuM** [comment]
Disable Expiry and MaxUnit in Edit

**Comment by ParshuM** [comment]
@amarN still its exits do check properly if it is done put screen shot

**Comment by ParshuM** [comment]
verify and closed
