### ISSUE TITLE
item (  while editing item not able to add taxes) 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#795]
steps 
1)create new item without adding taxes 
2)edit the same item and add taxes , give submit after that it will popup ( already added )

**Comment by gajananalienhu** [comment]
@GanuM 
create new item leave tax labels blank , again edit that item and add taxes and submit okay that time it will popup

**Comment by GanuM** [comment]
Can you post screenshot with console log @gajananalienhu

**Comment by GanuM** [comment]
Can you post screenshot with console log @gajananalienhu

**Comment by ParshuM** [comment]
verify and closed
