### ISSUE TITLE
if we delete item still its displaying in screen ( refresh problem )

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#796]
if we delete item still its displaying in screen ( refresh problem )

steps 
delete item and check 
go go different module than its not showing 
![image](https://cloud.githubusercontent.com/assets/24929491/25281336/eab8ccba-2661-11e7-969d-8d5f213f6f05.png)
![image](https://cloud.githubusercontent.com/assets/24929491/25281355/f46dd34a-2661-11e7-9e82-910e6dec1d5c.png)
![image](https://cloud.githubusercontent.com/assets/24929491/25281336/eab8ccba-2661-11e7-969d-8d5f213f6f05.png)

**Comment by GanuM** [comment]
working for me

**Comment by gajananalienhu** [comment]
@GanuM check in MAPP , try to delete , item suppliers customers okay , still deleted items will display on that screen  , its a refresh problem

**Comment by ParshuM** [comment]
verify and colsed
