### ISSUE TITLE
"Scan the bar-code it showing error (Item creation failed) ""Probaly after reading the bar-code its trying to submit the Item""."

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#798]
"Scan the bar-code it showing error (Item creation failed)
""Probaly after reading the bar-code its trying to submit the Item""."
![image](https://cloud.githubusercontent.com/assets/24929491/25281209/75698058-2661-11e7-888f-09e32020f706.png)

**Comment by ParshuM** [comment]
still exists

**Comment by dharwadkarR** [comment]
closed
