### ISSUE TITLE
in purchase module calendar drop down is not displaying  

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#801]
in purchase module calendar drop down is not displaying

**Comment by GanuM** [comment]
write proper discription @gajananalienhu

**Comment by dharwadkarR** [comment]
1.expiry date selected item add to cart
2.edit and give expiry to use drop down option
not able to show drop calender

**Comment by ParshuM** [comment]
still exist

**Comment by GanuM** [comment]
![image](https://cloud.githubusercontent.com/assets/13354052/25324031/feb1e4a0-28e0-11e7-9359-610a8042df6a.png)

@dharwadkarR  Cross check once again

**Comment by aafrinS** [comment]
verified and closed
