### ISSUE TITLE
Sales(suspended sales) 

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#806]
[] : In Sales when we do Suspend the sales .then the   unsuspend option is not there in the Mapp
![longscreenshot_2017-04-21-19-43-06](https://cloud.githubusercontent.com/assets/26079981/25301733/5011671c-274c-11e7-884b-9be2c494daf9.png)

**Comment by ParshuM** [comment]
still exist

**Comment by gajananalienhu** [comment]
already locked this bug
