### ISSUE TITLE
customer (Alignment Problem) 

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#807]
[ ] : there is Alignment Problem in the  Address module and comments module.
![longscreenshot_2017-04-21-18-59-53](https://cloud.githubusercontent.com/assets/26079981/25301783/407404bc-274d-11e7-9e5e-a60a2dd07416.png)

**Comment by Djprem** [comment]
put proper screen shot .........

**Comment by gajananalienhu** [comment]
@ajaykumarpatil  this is suppliers alignment not customers

**Comment by dharwadkarR** [comment]
closed
