### ISSUE TITLE
Sales( item view )

### ISSUE THREAD

**Issue by ajaykumarpatil** [GanuM/profitGuruPOS#808]

**Comment by ajaykumarpatil** [comment]
[ ] : there is alignment problem in the  item module.
![longscreenshot_2017-04-21-19-36-15](https://cloud.githubusercontent.com/assets/26079981/25301917/b27d1d12-274f-11e7-8a01-09f7bc700fb6.png)
  .

**Comment by ParshuM** [comment]
still exist

**Comment by ParshuM** [comment]
still exist

**Comment by ajaykumarpatil** [comment]
issue closed
