### ISSUE TITLE
Purchase screen UI issue 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#809]
i was using APP continuously for 15 minutes 
i did sales and went to purchase screen that time this problem arised 
![capt ure](https://cloud.githubusercontent.com/assets/20481449/25303697/fd3c1e04-2775-11e7-8716-a2e17ddd2520.PNG)
![capture](https://cloud.githubusercontent.com/assets/20481449/25303701/11364d30-2776-11e7-81aa-2e64a3971865.PNG)

lem arised

**Comment by aafrinS** [comment]
verified and closed
