### ISSUE TITLE
Take away displaying error pup-over 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#81]
Take away displaying error pup-over 
![01](https://cloud.githubusercontent.com/assets/20481136/21952048/2382df16-da38-11e6-9597-aeb248b903dc.png)

**Comment by amarN** [comment]
**issue still exits #81 
- [ ] not able to add customer
- [ ] not able to add item to cart and ones click to suspended sales it shows pop error**
![still exits](https://cloud.githubusercontent.com/assets/24929510/21961469/4b604016-db30-11e6-9014-80796de5c150.png)
![not able to add to card](https://cloud.githubusercontent.com/assets/24929510/21961480/9512ba04-db30-11e6-8e90-9ddf8b36fd32.png)

**Comment by Mseenu** [comment]
close
