### ISSUE TITLE
customer module: when u enter same email id it shows pop up message telling this email already exist then after changing the mail id if u give submit it is showing error object 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#811]
customer module: when u enter same email id it shows pop up message telling this email already exist
then after changing the mail id if u give submit it is showing error object
![err png2](https://cloud.githubusercontent.com/assets/25196499/25303914/efa1f22e-2779-11e7-89fa-16dffdd5a12f.PNG)

**Comment by GanuM** [comment]
@knayeem its working for me , cross check once again , close if it is working

**Comment by knayeem** [comment]
still exists

**Comment by knayeem** [comment]
closed
