### ISSUE TITLE
supplier ( when i editing the supplier phone number is not showing ) 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#813]
- [ ] when i editing the supplier phone number is not showing
![image](https://cloud.githubusercontent.com/assets/25196499/25304102/f4ce2976-277d-11e7-84bf-0f23c7b7cdea.png)

**Comment by dharwadkarR** [comment]
still exists

**Comment by ParshuM** [comment]
still exists

**Comment by ParshuM** [comment]
verify and closed
