### ISSUE TITLE
 In off site  MAPP 1) i m trying to create customer , item  and all.  2) it,s showing Error  like  " cannot read property  'error' of undefined "  it has to show proper error ...to identify user 

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#815]
In off site  MAPP 1) i m trying to create customer , item  and all.  2) it,s showing Error  like  " cannot read property  'error' of undefined "  it has to show proper error ...to identify user

**Comment by gajananalienhu** [comment]
@Djprem invalid bug
offsite mobile application is for only view purpose
