### ISSUE TITLE
in  MAPP customer module   when edit customer comment spelling  wrong 

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#818]
in customer module   when edit customer comment spelling  wrong 
![image](https://cloud.githubusercontent.com/assets/20493187/25304775/977b3530-278b-11e7-8a6c-763467219402.png)

**Comment by dharwadkarR** [comment]
still exists

**Comment by Mseenu** [comment]
here its working fine..plz cross checkh once again and close the issue

**Comment by dharwadkarR** [comment]
Closed
