### ISSUE TITLE
Reservation(while creating the table reservation then not able to select table.)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#82]
- [ ] while start creating the table reservation the not able to select table.
![aa r](https://cloud.githubusercontent.com/assets/24929491/21952362/acdc04ac-da3f-11e6-9853-38bf7269d0d3.png)

**Comment by GanuM** [comment]
@dharwadkarR this seems to be same as #96 , verify and close if it is duplicate

**Comment by GanuM** [comment]
duplicate of #47
