### ISSUE TITLE
store config( alignment problem in print setting )

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#822]
- [ ] alignment problem in print setting  
![screenshot from 2017-04-25 11 46 28](https://cloud.githubusercontent.com/assets/24929510/25371184/f39a4b3a-29ac-11e7-93a6-f7dfbbce8cb1.png)

**Comment by ParshuM** [comment]
alignment problem in print setting its done but hide the KOT printer

**Comment by knayeem** [comment]
still exists

**Comment by ParshuM** [comment]
#790
