### ISSUE TITLE
item module: alignment problem in category field "new" is not able to view

### ISSUE THREAD

**Issue by mafeela** [GanuM/profitGuruPOS#829]
alignment problem in category field "new" is not able to view in item module
![itemssss](https://cloud.githubusercontent.com/assets/26086810/25380491/fbf2cbf6-29cd-11e7-8092-b3ebc7cc4fe6.PNG)

**Comment by aafrinS** [comment]
item module : alignment problem in initial stock field
![alignment](https://cloud.githubusercontent.com/assets/25024115/25380782/1118cae8-29cf-11e7-9adf-b4f09cbb9367.png)

**Comment by ParshuM** [comment]
closed
