### ISSUE TITLE
supplier( editing supplier,displaying blank phone number) 

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#83]
- [ ]  while editing supplier phone number becomes blank'
![sup](https://cloud.githubusercontent.com/assets/24929491/21952560/62b3212e-da46-11e6-9dbc-3c55b4f48b07.png)
- [ ]  its not taking submit button.
- [ ] while creating new supplier displaying pop message while entering account number.
- [ ] while editing gender should be blank in retail.
![ss](https://cloud.githubusercontent.com/assets/24929491/21952572/bfbb3514-da46-11e6-8dc4-d8363e9eeba1.png)

**Comment by amarN** [comment]
- [ ] **while we edit supplier in comment text box .the tool tip is aligned in top of the comment box**
![tool line](https://cloud.githubusercontent.com/assets/24929510/21961696/0c556606-db37-11e6-8aac-849066c3ad99.png)

**Comment by Mseenu** [comment]
closed
