### ISSUE TITLE
Offsite application is showing error pop up( not showing proper alert)  Sale and purchase

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#830]
- [ ] Offsite application is showing error pop up(not showing proper alert) Sale and purchase
- [ ] Report is not showing it was showing error      
![7253391166303865475-account_id 1](https://cloud.githubusercontent.com/assets/24929491/25380483/2f63c0da-2965-11e7-813f-b5f5210f5291.png)
![3170801536242037200-account_id 1](https://cloud.githubusercontent.com/assets/24929491/25384208/518e1c3c-2974-11e7-9463-fc0ca7c31eba.png)

**Comment by gajananalienhu** [comment]
while we using offsite mobile we are getting error messages once we disconnect from server we should not get any error messages , if we do any process in offsite MAPP that time we should get messges like (Offsite mobile is only view-able) 
for view we should not get any error as well as messages

**Comment by dharwadkarR** [comment]
closed
