### ISSUE TITLE
   report: purchase detail report enhancement

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#831]
provide following fields in purchase detailed reports 
a. item name 
b. invoice date 
c. batch number
d.bill number 
e. supplier ID
f.category name 
e.tax amount 
f.tax percentage
g. received date 
h. received quantity.
add following filters in drop down .
1. purchase report item wise
2. purchase report batch wise
3.purchase report category wise 
4.purchase report distributor wise 

these fields are necessary to identify purchased items .

**Comment by moghribalakrishna** [comment]
Make this as Purchase History in Purchase Screen.
