### ISSUE TITLE
setup admin account password 

### ISSUE THREAD

**Issue by mafeela** [GanuM/profitGuruPOS#835]
while setting up password if we enter wrong password in confirmation password it shoud show warning message that confirmation password is wrong ,its showing only setup failed through that we doesnt identify the problem
![22](https://cloud.githubusercontent.com/assets/26086810/25417396/703df682-2a61-11e7-8dd9-0c88906a3501.PNG)

**Comment by aafrinS** [comment]
while setting up password if we enter wrong password in confirmation password it shoud show warning message that confirmation password is wrong ,its showing only setup failed through that we doesnt identify the problem

**Comment by ParshuM** [comment]
verify and closed
