### ISSUE TITLE
item (while creating item, after submission loading will happening after few second  showing error pop-up)

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#838]
- [ ] while creating item, after submission loading will happening after few second
       showing error pop-up

![sum error](https://cloud.githubusercontent.com/assets/25196499/25430403/2963a4b2-2a9a-11e7-9d95-7a84f12cbc6a.PNG)
[Uploading exception_20170426110716.txt

[Uploading info_20170426110716.txt

**Comment by aafrinS** [comment]
veified and closed
