### ISSUE TITLE
Item (In item if i delete  category unit and discount its not deleting 

### ISSUE THREAD

**Issue by knayeem** [GanuM/profitGuruPOS#841]
- [ ] In item if i delete  category unit and discount its not deleting 

![dele](https://cloud.githubusercontent.com/assets/25196499/25434197/05fb28ce-2aa9-11e7-8559-cdc46ff792d1.PNG)

**Comment by JamSameer** [comment]
The delete button is disable here..... if you want to delete category then you have to delete it from Application configuration.....

**Comment by aafrinS** [comment]
in application setting its getting deleted only from item screen its not getting delete .

**Comment by ParshuM** [comment]
verify and closed
