### ISSUE TITLE
in  employee module once we log in and do transaction. after that log out  .next time log in time it show's this error 

### ISSUE THREAD

**Issue by Djprem** [GanuM/profitGuruPOS#854]
in  employee module once we log in and do transaction. after that log out  .next time log in time it show's this error

**Comment by Djprem** [comment]
![done](https://cloud.githubusercontent.com/assets/20493187/25552786/206e9a6a-2cc0-11e7-9b68-d2ee836280d3.PNG)

**Comment by gajananalienhu** [comment]
steps to reproduce issue 
1) create new employee login from his credential 
logout and slide it left side that time all modules will display

**Comment by saichaitanyaeruvaram** [comment]
@JamSameer Test and mark it as bug fixed

**Comment by dharwadkarR** [comment]
closed
