### ISSUE TITLE
Item in that if i adding item MRP price more than to selling price its showing popover(selling price should be smaller than MRP) but in Mapp its not displaying 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#858]
![selling](https://cloud.githubusercontent.com/assets/20481136/25573702/74bd2856-2e65-11e7-91e3-30a19fbcb7cf.png)

**Comment by ParshuM** [comment]
![image](https://cloud.githubusercontent.com/assets/20481136/25573740/cbdc6c82-2e65-11e7-9fcc-1e7cd6531ab8.png)

**Comment by dharwadkarR** [comment]
closed
