### ISSUE TITLE
receiving(while editing quantity its not saving in reciving cart)

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#87]
- [ ] receiving(while editing quantity its not saving in receiving cart)
![rr](https://cloud.githubusercontent.com/assets/25024115/21954692/ac36554a-da7e-11e6-8065-5ee6104d23d4.png)

**Comment by amarN** [comment]
issue still exists .
- [ ] not able to edit and save.
- [ ] and if we edit one item it enables all the item.

**Comment by aafrinS** [comment]
- [ ] if  we do payment we are not able  get and see change due in the bill.

**Comment by dharwadkarR** [comment]
still exists

**Comment by saichaitanyaeruvaram** [comment]
@uzmaK @dharwadkarR :: Test all the cases listed above and then close.

Contact me if you have any queries

**Comment by uzmaK** [comment]
verified and closed
