### ISSUE TITLE
Display minimize and close option button DAPP 

### ISSUE THREAD

**Issue by gajananalienhu** [GanuM/profitGuruPOS#875]

**Comment by saichaitanyaeruvaram** [comment]
Please give advice on how to handle this.
1. Give minimize, maximize, restore buttons 
2. Open the nw window maximized and use the nodewebkit controls

My suggestion is Option:2

**Comment by saichaitanyaeruvaram** [comment]
https://github.com/nwjs/nw.js/wiki/Window

**Comment by moghribalakrishna** [comment]
Better we go ahead with Option 2.

**Comment by ParshuM** [comment]
verify and closed
