### ISSUE TITLE
taxes graphical reports taxes summary reports 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#892]
Display the taxes name 
 
![name tax](https://cloud.githubusercontent.com/assets/20481136/25749460/3dcc1b62-31cc-11e7-8e5b-d819e58358c5.png)
![taxes](https://cloud.githubusercontent.com/assets/20481136/25749485/4fa2374a-31cc-11e7-865b-dcccbaf3598e.png)

**Comment by aafrinS** [comment]
refer issue number 681
