### ISSUE TITLE
Place order 

### ISSUE THREAD

**Issue by ParshuM** [GanuM/profitGuruPOS#9]
1.over laps displaying  text items name  
![places order88](https://cloud.githubusercontent.com/assets/20481136/21680279/c1a853cc-d36e-11e6-8133-11db1a2f63cb.png)
2.if i add supplier name in place order it not displaying

**Comment by amarN** [comment]
still existed if supplier is add to place order it will not display to the name of supplier in place order
![no supplier name is display in](https://cloud.githubusercontent.com/assets/24929510/21802999/16302df6-d74e-11e6-9c61-7e81550736b1.png)

**Comment by gajananalienhu** [comment]
its working
