### ISSUE TITLE
Employee(while editing the employee its not displaying employee user name.) 

### ISSUE THREAD

**Issue by aafrinS** [GanuM/profitGuruPOS#90]
Employee(while editing the employee its not displaying employee user name.)

**Comment by aafrinS** [comment]
still exists not able edit user name.,and gender default not showing.

**Comment by aafrinS** [comment]
1. still we are not able to edit user name.
2. not able to submit once we edit employee.
3.in tool tips should show confirm password.
3. password is already present in password1.,when we edit employee.

**Comment by aafrinS** [comment]
still exist

**Comment by knayeem** [comment]
close.

**Comment by aafrinS** [comment]
still exist
