### ISSUE TITLE
Recieving(while recieving the serail no. item then pay & finish button not tekan)

### ISSUE THREAD

**Issue by dharwadkarR** [GanuM/profitGuruPOS#91]
- [ ] while receiving the serial no. item then pay & finish button not taken 
- [ ] and add  more the serial no item then item stock shows only one adding without pay & finish button takes. 
![12](https://cloud.githubusercontent.com/assets/24929491/21957432/eed6ae58-dabb-11e6-8f4b-20122865577f.png)
![11](https://cloud.githubusercontent.com/assets/24929491/21957434/f83763fc-dabb-11e6-85c2-dac0ea78470f.png)

**Comment by Mseenu** [comment]
closed
