### ISSUE TITLE
restaurant(submit button was not working and table screen is not move up/down)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#95]
- [ ] restaurant( let's when we take order submit button was not working and there is no option for go out from table list and screen is not move up/down)getting hanged.
![img-20170115-wa0013](https://cloud.githubusercontent.com/assets/24931488/21958233/9487381e-dacf-11e6-8455-263a3b8e969d.jpg)

**Comment by GanuM** [comment]
if you are not able to reproduce , then close this iisue @Mseenu

**Comment by Mseenu** [comment]
closed
