### ISSUE TITLE
reservation(table no.was not searching and text alignment problem in reservation detail and while making reservation "select table"button was not working)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#96]
- [ ] reservation(table no.was not searching.
- [ ]  and text alignment problem in reservation detail.
- [ ] and while making reservation "select table"button was not working)
![img-20170115-wa0012](https://cloud.githubusercontent.com/assets/24931488/21958399/51478c12-dad3-11e6-81ca-a2ca3c451c12.jpg)

![img-20170115-wa0008](https://cloud.githubusercontent.com/assets/24931488/21958375/fbbdfd80-dad2-11e6-8199-e18b814ebe15.jpg)

**Comment by amarN** [comment]
issue still exists #96

**Comment by GanuM** [comment]
duplicate of #47
