### ISSUE TITLE
takeaway(alignment problem )

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#97]
- [ ] takeaway(customer not adding to the sale and ant items not adding to cart)
- [ ] alignment problem
![img-20170115-wa0002](https://cloud.githubusercontent.com/assets/24931488/21958437/480dc9ee-dad4-11e6-9cc8-ac8aaa7c4899.jpg)

**Comment by amarN** [comment]
- [ ] able to add customer for sale .but not able to add item

**Comment by Mseenu** [comment]
closed and verified
