### ISSUE TITLE
customer(while editing customer without last name its takes submit)

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#98]
- [ ] while editing customer without last name its takes submit

**Comment by amarN** [comment]
issue still exist #98

**Comment by dharwadkarR** [comment]
issue still exist

**Comment by Mseenu** [comment]
still exist

**Comment by amarN** [comment]
- [ ] if we don't add last name in customer when we edit ,it takes submit

**Comment by amarN** [comment]
verified and issue closed
