### ISSUE TITLE
store config(in general configuration % symbol out of text box and tax word is missing)

### ISSUE THREAD

**Issue by amarN** [GanuM/profitGuruPOS#99]
- [ ] store config(in general configuration % symbol out of text box and tax word is missing)
![screenshot_2017-01-15-04-07-58](https://cloud.githubusercontent.com/assets/24929510/21958621/5730e150-dad8-11e6-880f-1b4382bdfb03.png)

**Comment by amarN** [comment]
tax is written but we need tax2 %.

**Comment by Mseenu** [comment]
closed and verified
